[Team-35][BE][쿠킴] PR 리뷰 적용과 로그인 구현 중
codesquad-members-2022/issue-tracker pull request #102
Opened 2022-06-17 16:17 UTC by ku-kim

안녕하세요 `Dion`! `쿠킴`입니다.
PR 늦게 보내드리게 되었네요. 죄송합니다. 😢
이번에는 이전 PR 리뷰 적용과 로그인을 구현하였습니다. (로그인하지 않은 유저에 대한 다른 페이지 접근 인증 구현은 아직 못했습니다.)

리뷰 감사합니다.! 😊
---

### 📝Description

#### 이전 PR 리뷰 적용 #33 
  - Graceful shutdown 적용
  - Spring Boot 다운 그레이(2.7.0 -> 2.6.7)
  - 로그 전략 수정

#### 깃허브 로그인 기능 구현

**Request**
클라이언트 측에서 authorization code를 포함하여 해당 url에 요청한다.
`GET /api/login/token?code={value}`

**Response**
응답 body json (accessToken와 유저 정보를 담아 전송한다.)

```json
{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
    "name": "kukim",
    "email": null,
    "avatarUrl": null
}
```

2022-06-17 16:27 UTC, ksundong commented
내일 아침에 리뷰해드릴게요 😊

2022-06-18 01:32 UTC, ksundong requested changes
안녕하세요. 쿠킴, 리뷰어 dion입니다.

## Questions

- 혹시 로그인 구현을 먼저하는 특별한 이유가 있나요?
  기능구현이 일주일동안 되지 않았던 것 같아서요~
- Graceful Shutdown 이 어떤 이유로 필요하다고 생각하고 적용해주셨나요?
- OAuth 인증에 대한 테스트는 어떤 식으로 수행해주셨나요?

고생하셨습니다.
리뷰드린 내용 참고해주시고, 고칠 부분은 고쳐주신 다음 일요일 저녁에 머지하겠습니다. 고생하셨어요.

2022-06-18 01:32 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/controller/request/TokenRequest.java
> +@Builder
`@Builder` 는 어떤 이유로 필요했나요?

2022-06-18 01:32 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/controller/response/LoginResponse.java
> +@Data
이런 식으로 `Lombok` 을 사용하진 말아주세요. 이렇게 작성하는 경우 어떤 Java Code가 매칭되는지 알고 사용하신걸까요?

2022-06-18 01:32 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/controller/response/TokenResponse.java
> +	private String tokenType;
여기는 왜 이런식으로 필드명 매핑을 해주셨나요?

2022-06-18 01:32 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/property/GithubProperty.java
> +}
의도하신건 `@ConfigurationProperty` 에 가까운 것 같아요.

2022-06-18 01:32 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +	}
private 메서드가 너무 많은데요 적절히 분리하는게 좋지 않을까요?
`LoginService` 가 담당해야 할 일이 있고, 아닌 것들을 구분해보세요.

2022-06-18 01:32 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +		return WebClient.create()
`WebClient` 를 사용해주신 이유는 무엇인가요?

2022-06-18 01:32 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +		return LoginResponseMapper.INSTANCE.map(user, accessToken);
이럴거면 mapstruct는 안쓰는 것이 좋겠네요.

2022-06-18 01:32 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +	@Id
가급적이면 어떤 방식으로 `Generation` 하는지도 붙여주는게 좋겠네요.

2022-06-18 01:32 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +@AllArgsConstructor
`@AllArgsConstructor` 는 잠재적으로 문제를 갖고 있는데요.
한 번 `User` 에 변경이 일어난다고 생각하고, 어떤 것이 문제가 될지 생각해보세요.

2022-06-18 01:32 UTC, ksundong commented on be/src/main/resources/application.yml
> +    context-path: /api
주석에 사소한 오타가 있네요.

2022-06-18 01:32 UTC, ksundong commented on be/build.gradle
> +    testImplementation 'io.rest-assured:rest-assured'
얘는 왜 추가되었나요?

2022-06-18 03:10 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/controller/request/TokenRequest.java
> +@Builder
TokenRequest 객체를 생성할 때 빌더를 사용했습니다.!

LoginService.getToken(code)
```java
		TokenRequest tokenRequest = TokenRequest.builder()
			.clientId(githubProperty.getClientId())
			.clientSecret(githubProperty.getClientSecret())
			.code(code)
			.build();
```

2022-06-18 03:16 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/controller/response/TokenResponse.java
> +	private String tokenType;
JsonNaming과 JsonProperty 사용이 일치되지 못한 거 같습니다.

2022-06-18 03:26 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/controller/response/LoginResponse.java
> +@Data
Lombok 사용을 남발했습니다. :-( 

Lombok으로 보일러플레이트가 사라지겠지만, 실제 구현체들이 너무 많은 코드가 매칭될 거 같습니다.
빈 생성자, 전체 생성자, 전체 생성자에 맞는 빌드 패턴, Data가지고 있는 게터,세터,tostring  ... 
롬북 사용에 주의하겠습니다!

2022-06-18 04:11 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/property/GithubProperty.java
> +}
`@ConfigurationProperties` 소개주셔서 감사합니다.

ConfigurationProperties 는 EnableConfigurationProperties 프로퍼티 클래스 등록해야하지만,  @Value에 비해 한번에 프로퍼티를 설정할 수 있고 값 검증과 값 매핑이 유연한 장점을 가지고 있군요.!

2022-06-18 04:12 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +	}
(토큰을 얻고, Github 유저정보를 얻어오는 )GithubOAuth 처리 관련 서비스를 별도로 구분할 수 있겠다고 생각이 듭니다.!

2022-06-18 04:37 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +		return WebClient.create()
Spring 내에서 외부 HTTP 요청할 때 사용하기 위해서입니다.(HTTP 클라이언트)

현재 사용되는 곳은 Github Server에게 Github의 AccessToken과 User 정보를 받기 위해서 사용됩니다.

HTTP 클라이언트 기술 중 RestTemplate, WebClient를 찾았습니다. WebClient가 RestTemplate에 비해 속도가 빠르고 비동기성을 보장한다고 보았습니다. 

RestTemplate는 공식 문서에서 Spring 5.0 버전 부터 WebClient 사용을 권장하고 있어 사용하게 되었습니다. 

하지만 현재 webclient에서 사용하고 있는 처리는 block, 비동기/블록킹 방식으로 사용하고 있습니다.

비동기/non-blocking 으로 작동하는 코드를 사용할 수 있는지 좀 더 찾아보아야 할 거 같습니다.!

---

reference

- [spring doc restTemplate 안내](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html)
- [동기와 비동기 with webClient](https://tecoble.techcourse.co.kr/post/2021-10-20-synchronous-asynchronous/)

2022-06-18 04:38 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +		return LoginResponseMapper.INSTANCE.map(user, accessToken);
이번 프로젝트에서 `mapstruct` 를 처음 사용해보았는데요.!
혹시 어떤 이유에서 쓰지 않는것이 좋다고 말씀하신걸까요?

2022-06-18 04:43 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +	@Id
현재 Id는 Github에서 제공해주는 별도의 유니크한 id를 사용하고 있어, 유니크한 id로 PK를 잡으면 되겠다고 생각하여 Generation 방식을 사용하지 않았는데요.

되돌아보니 Github 에서 제공해주는 유니크한 아이디로 구분한다면 , 향후 Github 이외의 유저의 id를 매핑해주기 어려울 거 같다는 생각이드네요.

Github에서 제공해주는 id는 별도의 id로 구분하고(third party id) 자체 id를 두어야겠다고 생각을 했습니다.

2022-06-18 04:47 UTC, ku-kim commented on be/build.gradle
> +    testImplementation 'io.rest-assured:rest-assured'
Login 테스트를 하려고 추가해주었는데요.!
테스트 관련 작성하다 아직 구현하지 못해 PR 보내지 못했지만, 의존성만 들어가게 되었네요 😢

2022-06-18 04:48 UTC, ku-kim commented on be/src/main/resources/application.yml
> +    context-path: /api
자세하게 봐주셔서 감사해요!

2022-06-18 05:36 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +@AllArgsConstructor
AllArgsConstructor 는 자동생성 되는 장점이 있지만 자동 생성이 문제인 것 같습니다.

1.  멤버변수의 순서를 바꿀 때 문제가 될 수 있습니다.
같은 타입의 멤버 변수 순서를 바꾼다면 생성자가 다시 만들어집니다. 이때 다른 값이 들어갈 수 있는 문제가 있습니다.

2. 멤버변수 추가, 삭제
멤버변수의 추가, 삭제 시 기존 운영코드가 깨져 수정하는 것은 같지만, 생성자가 의도적으로 명시되어있는 코드와 자동생성되는 문제가 있어 보입니다.

생성자나 팩토리 메서드, 생성자에 @Builder를 붙여 사용하면 위 문제를 피할 수 있다고 생각합니다.
무분별한 lombok 사용을 항상 주의해야겠네요.!   

---

reference

https://kwonnam.pe.kr/wiki/java/lombok/pitfall

2022-06-18 06:14 UTC, ku-kim commented
늦게 PR 보냈지만 빠른 리뷰해주셔서 죄송하고 감사합니다. 🙇‍♂️

- 혹시 로그인 구현을 먼저하는 특별한 이유가 있나요? / 기능구현이 일주일동안 되지 않았던 것 같아서요~
  - A) FE와 회의하며 로그인을 먼저 구현하기로 했습니다.! 말씀처럼 이번주는 기능 구현보다는 배포와 로그인에 집중하게되었습니다. 모두 처음 도전해본 기술이라 익숙하지 않고 학습하며 진행하게 되었습니다. :D 
- Graceful Shutdown 이 어떤 이유로 필요하다고 생각하고 적용해주셨나요?
  - A) kill -9 로 바로 종료하면 이전의 연결되어있던 클라이언트(스레드) 작업이 더이상 진행되지 않고 종료되어 문제가 발생할 수 있다고 생각했습니다. kill -15 로 정상 종료 시그널을 보내고, spring에서 graceful shutdown으로 설정하여, 더이상 추가적인 클라이언트의 접속은 허용하지 않지만, 기존의 처리중이던 작업은 완료 후 종료할 수 있습니다.! 새로운 배포가 되었을 때 이전 서버에 대한 graceful shutdown Timeout 옵션을 20초로 주게 되었고,  최종적으로 25초를 기다린 뒤 새로운 서버를 띄우게 되었습니다. 타임아웃 20초와 종료까지 5초의 텀이 긴지 짧은지는 명확하게 인지는 못한 상황입니다. 
- OAuth 인증에 대한 테스트는 어떤 식으로 수행해주셨나요?
  - A) 통합테스트로 외부 시스템(Github Server)는 테스트 대역으로 지정하여 테스트하려고 계획했으나 OAuth는 처음이라 당장 적용할 순 없었습니다. 불편하지만 간단한 로그인 버튼 html과 postman을 활용해 손테스트(?)로 하였습니다. :D , 리팩토링할때마다 손으로 테스트해야하는 어려움이 있었고.. 빨리 테스트코드를 작성해야겠다고 생각이 들었습니다.!

---

주말까지 리뷰해주셔서 감사하빈다. 즐거운 주말되세요 😆

2022-06-18 15:01 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/controller/request/TokenRequest.java
> +@Builder
음, 이렇게 만들어 줄 때, 혹시 개발자가 실수로 `code`를 누락하면 어떻게 동작할까요?
이를 알아챌 수 있는 방법은 있을까요?

2022-06-18 15:15 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +		return WebClient.create()
비동기 블로킹은 동기 블로킹과 거의 차이가 없습니다. 동기/비동기, 블로킹/논블로킹은 면접문제로도 자주 나오니 한 번 학습해두시는걸 추천드립니다.
참고하신 글도 잘 이해했다고는 볼 수 없습니다. 동기/비동기는 동기 비동기고, 블로킹/논블로킹은 블로킹 논블로킹입니다.
쿠킴이 사용하기에 `RestTemplate`은 무엇이 부족했나요?
`WebFlux` 의존성은 꽤 커서, `WebClient` 만을 사용하기 위해 `WebFlux` 의존성을 가지고 오는건 닭을 잡기위해 소잡는 칼을 쓰는것과 비슷하다고 봅니다.
스프링 외부로 눈을 돌리면 여러 HTTP Client Library가 있는데요. 그건 고려해보셨는지 궁금하네요~

2022-06-18 15:17 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +		return LoginResponseMapper.INSTANCE.map(user, accessToken);
아 조금 잘못 적었네요. `mapping` 라이브러리 사용은 별로 추천드리지 않습니다.
저런 `mapping` 라이브러리가 출현한 이유는 거대한 클래스 때문입니다. 당연히 이건 안티패턴입니다.
이런 작은 클래스는 그냥 직접 변환시켜주세요.

2022-06-18 15:18 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +	@Id
네 가급적이면 외부 id는 신뢰하지 말아주세요.
통제할 수 있는 것을 id로 삼아주세요.

2022-06-18 15:20 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +@AllArgsConstructor
네 1번은 같은 타입을 속성으로 중복해 사용하지 말라는 설계 지침도 있을정도로 문제가 됩니다.
`@Builder`는 역시 무분별한 사용에 가깝습니다.

2022-06-18 15:23 UTC, ksundong commented
- FE와 회의했다면 괜찮습니다.
- 시간은 직접 측정하셔야 합니다. 서버 스펙, 의존성의 종류, 버전에 다 영향을 받기에 직접 측정하는게 맞습니다. 사실 graceful shutdown 이라면 health check를 지속적으로 해주면 되겠죠. 아니면 죽을 때 이벤트를 발생시키거나요.
- 넵넵

2022-06-18 15:36 UTC, ksundong approved these changes
고생하셨습니다. 쿠킴! 몇가지 추가 리뷰를 남겼습니다.
리뷰 내용 참고해주시고, 일요일 오후에 머지하도록 할게요~

2022-06-18 15:36 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/property/GithubProperty.java
> +@Component
얘는 다른걸로 바꾸는게 좋지 않을까요?

2022-06-18 15:36 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/service/GithubOAuth.java
> +@RequiredArgsConstructor
`@RequiredArgsConstructor`도 `@AllArgsConstructor` 와 마찬가지입니다.
편하긴 할텐데, 별로 좋진 않습니다.

2022-06-18 15:36 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +			userRepository.save(UserMapper.INSTANCE.map(githubUserResponse)));
`orElseGet()` 을 이렇게 이용하는건 처음보네요. 괜찮은 것 같습니다. 👍

2022-06-18 15:36 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +	}
이렇게 하면 `id`는 어떻게 할당시켜줄 수 있을까요?

2022-06-18 15:36 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/property/GithubProperty.java
> +public class GithubProperty {
생성자 주입을 받아서 사용할 수도 있습니다.

2022-06-19 16:29 UTC, merged

2022-06-21 02:58 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/controller/request/TokenRequest.java
> +@Builder
code를 실수하면 알아챌 수 있는 방법이 없고, 실수하기도 좋을 거 같습니다. 
또한 빌더 패턴은 @Builder 사용하지 않는다면 별도의 빌더도 만들어야하고, 매개변수가 적을 때는 팩토리 메서드나 생성자만으로 사용하는것이 강제성을 띄워 실수도 적을 거 같습니다.!

2022-06-21 03:05 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +		return WebClient.create()
말씀처럼 WebFlux 의존성이 커 소잡는 칼을 닭잡기 하는 느낌도 공감되네요!
되돌아 보니 `RestTemplate` 만으로 충분했지만, 이전 프로젝트에서 `RestTemplate`를 사용해봐서 이번엔 WebClient를 사용해보고싶은 욕심이 있었습니다. 😅

외부 HTTP Client Library는 고려해보지 못했습니다.!
말씀 주셔서 찾아보니
Apache의 HttpClient, 기본 JDK의 HttpURLConnection, Square의 OKHttp, Retorfit 등 등 정말 많은 외부 라이브러리가 있겠군요
기술 선택에 항상 고민과 사용한 이유에 대해 고민해야겠군요.!

2022-06-21 03:09 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +	@Id
넵! 감사합니다.

2022-06-21 03:10 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +@AllArgsConstructor
롬북을 사용한 `@AllArgsConstructor`. `@Builder`, `@ RequiredArgsConstructor` 사용을 무분별하게 사용하지 않아야겠습니다.!

2022-06-21 03:19 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/property/GithubProperty.java
> +@Component
넵!

2022-06-21 03:21 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +			userRepository.save(UserMapper.INSTANCE.map(githubUserResponse)));
return을 한번에 처리해보았는데..ㅎㅎ 감사합니다.!

2022-06-21 03:26 UTC, ku-kim commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +	}
`id`는 auto increment 로 할당하고 있어서 객체에선 생성하지 않고 있는데요.!
어떻게 할당시켜준다는 질문을 이해를 잘 못했습니다.!
JPA가 id를 어떻게 할당시켜주는지 말씀이실까요?

2022-06-21 15:44 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/controller/request/TokenRequest.java
> +@Builder
네 빌더패턴이 안티패턴인 이유가 여러개 나옵니다.

1. 누락된 필드가 `null`로 세팅됨
2. 컴파일러가 알아챌 수 없음(제일 좋은 오류는 컴파일 에러라는 말 아시죠? ㅎㅎ)
3. 클래스의 필드가 많아지는 code smell을 알아채기 어렵게 만듦

사실 자바 언어 디자인의 문제여서, 어쩔 수 없이 쓰는 패턴이고요.
이를 위해서 안전한 빌더패턴이 고안되었습니다. 빌더패턴을 쓰고싶다면 안전한 빌더패턴을 사용해주세요.

2022-06-21 15:45 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +		return WebClient.create()
네 면접가면 지겹도록 들으실 수 있을겁니다.

2022-06-21 15:46 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
> +		return LoginResponseMapper.INSTANCE.map(user, accessToken);
네 학습을 위해서 사용해볼 수는 있는데, 솔직히 몰라도 회사에서 쓰면 그 때 배우면 되는 기술입니다.
그 어떤 회사도 우리는 `mapstruct`를 써요 라고 하지 않는걸 보시면 아실 수 있습니다.
자격요건에도 없고요. 전 오히려 있던 `mapstruct`를 걷어낸 전적이 있습니다 ㅋㅋㅋ..

2022-06-21 15:49 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/user/domain/User.java
> +	}
이게 기술하고 너무 깊이 엮여버려서 드린 코멘트입니다.
JPA 없이 이 클래스는 의미가 없는 클래스인가요?

2022-06-21 15:50 UTC, ksundong commented on be/src/main/java/dev/kukim/issues/user/auth/property/GithubProperty.java
> +public class GithubProperty {
네, 이렇게 작성해주면 보다 안전한 코드가 됩니다.