[Team-21][BE][루이1세] 1주차 두번째 PR
codesquad-members-2022/issue-tracker pull request #108
Opened 2022-06-19 09:56 UTC by Louie-03

## 인사말
안녕하세요 시그리드! 루이 & 한세입니다 😄
이번에는 OAuth 관련 학습 & 구현을 진행했습니다.

## 진행 사항
- PR 리뷰 반영
  - [리뷰 반영한 API 명세서](https://petal-fowl-d1d.notion.site/API-b7283ab35e1244ecb383585137255850)
- GitHub OAuth API를 사용한 GitHub 사용자 정보 조회
- DB에 저장되지 않은 사용자에 한해서 사용자 정보를 DB에 저장하는 로직 구현
- Member(사용자) 엔티티 구현, 연관관계 매핑  

<details>
    <summary><h2>Entity ERD</h2></summary>
<img src="https://user-images.githubusercontent.com/92966772/174475498-07ad60f9-2f68-4b91-b801-6d5f6887218d.png">
</details>

2022-06-19 22:41 UTC, sigridjineth approved these changes
안녕하세요, Sigrid Jin입니다.
리뷰 남겨드렸으니 확인 부탁드립니다. 이번 한 주도 빠샤 하세요~! ✨✨✨✨✨

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/IssueTrackerApplication.java
> +@ConfigurationPropertiesScan
`@ConfigurationPropertiesScan` 를 사용했을 때의 이점은 무엇일까요? 스캔하는 범위는 어디서부터 어디까지 일까요? (패키지) 동작 방식에 대해서도 설명해주세요.

[링크](https://stackoverflow.com/questions/59674619/how-is-configurationproperties-annotated-classes-detected-automatically-with-s)

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/controller/LoginController.java
> +        return ResponseEntity.status(HttpStatus.SEE_OTHER)
302 SEE_OTHER를 택하신 이유가 있을까요? HTTP 300번대 redirect 중에서 302를 택한 이유에 대해 설명해주세요.

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/domain/Issue.java
> +    private List<IssueLabel> issueLabels = new ArrayList<>();
`@OneToMany` 에서 List를 사용하는 것과, Set을 사용하는 것에는 어떠한 차이가 있을까요?

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/domain/Issue.java
> +    @Enumerated(EnumType.STRING)
`Enumerated` 는 어떠한 방식으로 동작하나요? `Converter` 에 대해서 알고 계시나요?

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/domain/IssueLabel.java
> +    @ManyToOne
`fetchType` 을 명시해주세요. 설정은 명시적으로 가져가는 것이 좋다고 생각합니다.

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/oauth/GithubAccessToken.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
`JsonNaming` 의 사용 👍

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/oauth/OAuthService.java
> +            .blockOptional()
WebClient를 사용했을 때 `block` 을 활용하면 사용한 의미가 없을텐데요. 왜 그럴까요?

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/oauth/OAuthService.java
> +        return WebClient.create()
WebClient가 등장했습니다. 해당 라이브러리가 왜 등장했고, RestTemplate을 사용하지 않고 이 라이브러리를 채택한 이유에 대해 설명해주세요.

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/repository/MemberRepository.java
> +    boolean existsBySocialId(String socialId);
`nit`

`MemberRepository` 라면 명시적으로 Repository에서는 Member 객체를 반환하는 역할만 수행하는 것이 올바른 함의 아닐까요? Member 외의 다른 역할 수행 (예; 존재 여부 판단) 을 직접적으로 하는 행위는 Repository 객체가 수행해야 하는 역할 밖을 벗어났다고 생각합니다.

간단한 경우에는 `existsBy` 를 사용해도 되겠지만, 조건문이 3개 이상이거나, 필드명이 너무 길거나 조건문 자체가 복잡한 경우 등에는 `@Query` 를 이용해야 합니다. 그런데 JPQL은 또 `select exists` 문법을 지원하지 않기 때문에 `count` 를 우회하는 방법에 대해 고민해야 하고 그렇죠. 성능적인 이슈에서 쿼리를 때릴 필요가 없다면 socialId로 object를 가져오려 하고 없다면 `Optional orElse` 로 반환하는 것을 개인적으로 선호합니다.

이는 전적으로 개인적인 생각이기 때문에 편하게 의견 남겨주세요.

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +@Transactional(readOnly = true)
`@Transactional` 을 class에 붙이면 어떤 특징이 있을까요? 메소드 레벨에서 이미 `@Transactional` 을 붙였는데 클래스 레벨 전체에 정의할 필요가 있을까요? 있다면 어떤 지점일까요?

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +        if (!existsBySocialId) {
제가 위에서 말한 내용을 실전적으로 적용해보려면 Null Object Pattern에 대해서도 학습해보시면 좋을 것 같군요.

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +            memberRepository.save(member);
JPA Repository에서 `save` 한다는 행위는 대체 무엇일까요?

2022-06-19 22:41 UTC, sigridjineth commented on BE/src/test/java/louie/hanse/issuetracker/IssueTrackerApplicationTests.java
> +		memberRepository.existsBySocialId("dfae");
안 쓰시는 테스트 코드라면 지워주세요.

2022-06-19 22:42 UTC, sigridjineth commented
API 명세서에서, Body에 반환 값이 없다면 "없음" 이 아니라 빈 JSON 객체를 남겨주세요.

```
{}
```

2022-06-20 01:38 UTC, rkolx commented on BE/build.gradle
> +	implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.8.0'
쿼리 파라미터를 로그로 남기는 외부 라이브러리는 시스템 자원을 사용하므로, 개발 단계에서는 편하게 사용해도 되지만 운영시스템에 적용하려면 꼭 성능테스트를 하고 사용하는 것이 좋은걸로 알고 있습니다.

2022-06-20 01:54 UTC, rkolx commented on BE/src/main/java/louie/hanse/issuetracker/IssueTrackerApplication.java
> +@ConfigurationPropertiesScan
`@EnableConfigurationProperties`를 이용해 `@ConfigurationProperties`를 사용하는 경우 해당 클래스들이 많아지면 코드가 무거워지는 한계가 있었는데, SpringBoot 2.2부터는 이러한 문제점들을 해결하기 위해 `@ConfigurationPropertiesScan` 이라는 어노테이션을 제공하여 패키지 범위로 해당 어노테이션을 스캔하기 때문에 관리가 용이해졌습니다. 
스캔 범위는 해당 어노테이션이 존재하는 패키지 범위로 작동을 하는 걸로 알고 있습니다.

2022-06-20 02:15 UTC, rkolx commented on BE/src/main/java/louie/hanse/issuetracker/controller/LoginController.java
> +        return ResponseEntity.status(HttpStatus.SEE_OTHER)
301(영구적)과 302(임시적)의 차이에 대해서 알아봤는데 저희가 좀 더 공부를 하고 답변을 다는 걸로 하겠습니다 😢

2022-06-20 02:39 UTC, rkolx commented on BE/src/main/java/louie/hanse/issuetracker/domain/Issue.java
> +    private List<IssueLabel> issueLabels = new ArrayList<>();
어떤 컬렉션 타입이 더 나을지 고려하지 않고 쓴 부분인데 시그리드 질문을 보고 아차싶었습니다ㅠㅠ
찾아보니, JPA구현체인 하이버네이트는 List를 Bag으로 바꿔 동작하는데 이때 Bag안에 엔티티 하나를 지우게 되면 `모든데이터 삭제 쿼리 + 기존 존재하는 데이터 재삽입`의 과정이 일어나게 됩니다. 그에 반면 Set은 쿼리가 하나만 나가기 때문에 이러한 경우를 고려한다면 Set을 사용하는게 맞는것으로 보입니다. 
다음부터는 엔티티의 속성을 고려하여 컬렉션타입을 사용하겠습니다!

[참고자료](https://stackoverflow.com/questions/4655392/which-java-type-do-you-use-for-jpa-collections-and-why)

2022-06-20 03:14 UTC, rkolx commented on BE/src/main/java/louie/hanse/issuetracker/domain/Issue.java
> +    @Enumerated(EnumType.STRING)
`@Enumerated`의 기본은 순서를 저장하고, EnumType에 STRING옵션을 사용하면 string 자체의 값으로 저장하게 됩니다. 그리고 Enum을 적절한 value로 변환시켜 관리 하려면 `@Converter` 어노테이션을 이용하여 관리 규칙을 지정하여 사용할 수 있습니다.

2022-06-20 03:22 UTC, rkolx commented on BE/src/main/java/louie/hanse/issuetracker/oauth/OAuthService.java
> +            .blockOptional()
WebClien는 `Non-Blocking` 방식을 지원하기 때문에 `block`과 같이 작업이 끝날 때까지 백그라운드에서 작업이 끝났는지 지속적으로 확인 하지 않아도 됩니다!

2022-06-20 03:24 UTC, rkolx commented on BE/src/main/java/louie/hanse/issuetracker/oauth/OAuthService.java
> +        return WebClient.create()
기존의 동기 API도 제공할 뿐만 아니라, Non-Blocking 및 비동기 접근 방식을 지원하여 효율적인 통신이 가능하여 해당 라이브러리를 채택하게 되었습니다.

2022-06-20 03:29 UTC, rkolx commented on BE/src/main/java/louie/hanse/issuetracker/repository/MemberRepository.java
> +    boolean existsBySocialId(String socialId);
Member의 정보 중 중복 판단 여부를 가릴 수 있는 SociaId를 이용하여 간단하게 구현하고자 하는 것이 목표였습니다😳
추후 복잡해질 경우 시그리드가 말씀해주신 부분 참고하여 사용해보도록 하겠습니다!.!

2022-06-20 03:34 UTC, rkolx commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +@Transactional(readOnly = true)
메서드 레벨에서 `@Transactional`을 붙이지 않은 메서드중 퍼블릭메서드는 class 레벨에 붙인 어노테이션을 그대로 사용하게됩니다. 
추후 추가되는 조회용 메서드를 고려하여 class레벨에 해당 어노테이션을 붙여주었습니다.

2022-06-20 03:39 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/IssueTrackerApplication.java
> +@ConfigurationPropertiesScan
대체 어떻게 컴포넌트 스캔을 하길래 마법같은 일이 일어날까요? 시간이 되실 때 꼭 찾아보고 고민해보세요.

2022-06-20 04:05 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/oauth/OAuthService.java
> +            .blockOptional()
우리가 WebClient를 사용하고 있는데요, 어떤 점에서 이 라이브러리를 가져왔는지를 고민할 필요가 있겠습니다.
어떤 점이 RestTemplate 사용을 주저하게 만드셨나요? WebClient를 사용하기 위해서는 WebFlux를 사용해야 하는데, WebClient에 너무 의존성이 큰 라이브러리입니다.

동기 vs 비동기, 블로킹 vs 논블로킹에 대해서도 한번 공부해보시길 추천드립니다.
WebClient를 제외하고도 HttpURLConnection, HttpClient, OkHttp 등 여러 HTTP 라이브러리가 있습니다.
WebClient를 사용하지 마라는 것은 아닌데, Reactive에 대한 학습이 이루어지지 않을 것이라면 지금은 적당한 수준에서 커트할 필요가 있습니다.

이 글을 꼭 읽어보시고 생각해주세요.
[참고할 링크](https://jypthemiracle.medium.com/servletcontainer%EC%99%80-springcontainer%EB%8A%94-%EB%AC%B4%EC%97%87%EC%9D%B4-%EB%8B%A4%EB%A5%B8%EA%B0%80-626d27a80fe5)

2022-06-20 04:05 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +@Transactional(readOnly = true)
제 의견은 메소드 별로 일일이 `@Transactional` 을 명시적으로 달아주는 것이 훨씬 개발자의 의도를 잘 파악할 수 있다고 생각합니다.

2022-06-20 07:53 UTC, rkolx commented on BE/src/main/java/louie/hanse/issuetracker/IssueTrackerApplication.java
> +@ConfigurationPropertiesScan
시간될 때
 학습해보도록 하겠습니다!

2022-06-20 08:13 UTC, rkolx commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +            memberRepository.save(member);
`save()` 메서드 하나로 저장 및 병합을 처리할 수 있습니다. 새로운 값이라면 `persist()`로 영속화하고 존재하는 값이라면 한번 영속화되었던 엔티티로 판단하여 `merge()`를 수행합니다. 즉 신규 데이터를 저장하는것뿐만 아니라 변경된 데이터의 저장이라는 의미도 포함합니다. (아래와 같은 코드를 참고하였습니다)
``` 
public <S extends T> S save(S entity) {
    Assert.notNull(entity, "Entity must not be null.");

    if (entityInformation.isNew(entity)) {
        em.persist(entity);
        return entity;
    } else {
        return em.merge(entity);
    }
}

2022-06-21 13:52 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +            memberRepository.save(member);
JPA Repository의 `save` 를 사용할 때 주의해야 할 사항이 있다면 무엇일까요?

2022-06-21 13:56 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +            memberRepository.save(member);
만약 `Id` 가 `@GeneratedValue` 형태로 값을 주입받는 상황이 아니라면 어떻게 될까요?
예제 코드는 다음과 같습니다.
```java
@Entity
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Member {

    @Id
    @Column
    private String email;

    private String name;

    private Member(String email, String name) {
        this.email = email;
        this.name = name;
    }

    public static Member createMember(String email, String name) {
        return new Member(email, name);
    }
}
```

2022-06-21 13:59 UTC, sigridjineth requested changes
추가로 몇 개 리뷰 커멘트를 달았습니다.

2022-06-21 13:59 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +        if (member == null) {
여기서 `null` 을 직접 다루는 것은 위험합니다. 왜 그럴지 생각해봅시다. 개인적으로 Null Object Pattern의 적용을 추천드립니다.

2022-06-21 13:59 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/service/OAuthService.java
> +            .block();
다시 말씀드리지만 WebClient의 사용이 최선일 지 고민해주세요.

2022-06-21 13:59 UTC, sigridjineth commented
머지하겠습니다. 위의 커멘트가 아직 해결되지 않은 내용이 다소 있는데요, 꼭 답변 남겨주시기 바랍니다.

2022-06-21 14:00 UTC, merged

2022-06-22 02:26 UTC, Louie-03 commented on BE/src/test/java/louie/hanse/issuetracker/IssueTrackerApplicationTests.java
> +        throw new RuntimeException();
사용하지 않는 테스트 코드입니다. 지우도록 하겠습니다 😀

2022-06-22 02:27 UTC, Louie-03 commented on BE/src/main/java/louie/hanse/issuetracker/service/OAuthService.java
> +            .block();
이전 프로젝트에서 RestTemplate을 사용했어서 이번에는 WebClient를 한번 사용해보고 싶었습니다!
추후에 RestTemplate와 WebClient의 장단점을 학습하는 시간을 가져보도록 하겠습니다 😄

2022-06-22 02:38 UTC, Louie-03 commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +        if (member == null) {
위에서 시그리드가 달아주신 리뷰처럼 socialId로 object를 가져오려 하고 없다면 Optional orElse 로 반환하는 로직을 구현해봤습니다!
Null Object Pattern에 대해 학습해봤지만 해당 코드에 Null Object Pattern을 어떻게 적용해야할지 감이 잘 안잡히는데 혹시 조금 더 설명 부탁드려도 될까요?!

2022-06-22 02:47 UTC, Louie-03 commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +            memberRepository.save(member);
Id가 @GeneratedValue 형태로 값을 주입받는 상황이 아니라면 해당 엔티티를 저장할 때 Id를 직접 할당해줘야 합니다 😀

2022-06-22 02:49 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +        if (member == null) {
`null` 을 그대로 반환하는 것이 아니라, 예를 들어 `NoneMember` 라는 객체를 만드는 것입니다.
이후, Optional에서 `null` 값일 때 `orElseGet` 을 실행하여 `NoneMember` 라는 객체를 반환하도록 구현할 수 있겠습니다.

2022-06-22 02:51 UTC, Louie-03 commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +            memberRepository.save(member);
save 메서드를 사용할 때 이미 엔티티가 영속화가 되어있던 적이 있다면 entityManager.merge()를 실행합니다.
entityManager.merge()는 모든 필드의 값이 update 되므로 주의해야합니다.
JPA의 변경 감지 기능을 사용한다면 변경된 필드만 update 되기 때문에 되도록이면 변경 감지 기능을 사용하면 좋을 것 같습니다 😀

2022-06-22 02:53 UTC, sigridjineth commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +            memberRepository.save(member);
회원가입을 할 때 사용자가 입력한 이메일이 PK로 설정했으면 `isNew(entity)` 메서드가 `String email` 변수를 확인하죠.
`null` 이 아닌 값으로 채워져 있으므로 `em.merge(entity)` 메서드를 실행하게 될 것입니다.
그런데 회원가입을 통해 입력한 이메일이 실제로 존재하는지 확인하기 위해 SELECT 쿼리를 하나 보내게 되겠죠?

순수하게 save를 하고 싶은데 별도의 SELECT 쿼리가 더 날라가는 비효율이 발생하는 것입니다.
이럴 때는 `interface Persistable <String>` 를 implement한 뒤에 `isNew` 메소드를 직접 오버라이딩하여 비교할 대상을 직접 지정하는 것이 가능해져요.

2022-06-22 03:22 UTC, Louie-03 commented on BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
> +            memberRepository.save(member);
답변 감사합니다 시그리드! `@GeneratedValue`를 사용하지 않고 PK를 직접 할당하는 경우에 추가로 SELECT 쿼리가 발생하는 것을 확인했습니다! 
이런 비효율적인 부분을 isNew 메서드를 직접 오버라이딩해서 비교할 수도 있군요 🤩