[Team-30] [BE] 2주차 첫 번째 PR
codesquad-members-2022/issue-tracker pull request #110
Opened 2022-06-20 12:12 UTC by nathan29849

안녕하세요 Dan! 이번 프로젝트를 함께 하게된 나Dan이라고 합니다! 

지난 주에 배포를 하려고 하다가 nginx 문제가 자꾸 해결이 안돼서 
결국 기능구현을 하지 못하고 PR을 날리지 못했습니다 ㅠㅠ

이번 주 주된 진행사항은 다음과 같습니다
- Spring Interceptor를 이용한 OAuth Login 처리
- Custom Exception 만들어 OAuth 관련 Exception 처리

디테일한 사항은 comment로 남기겠습니다!

2022-06-20 12:13 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/BeApplication.java
>  	public static void main(String[] args) {
결국 Front에서 쓰는 정보가 아니게 되어 삭제하였습니다.

2022-06-20 12:14 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/common/config/WebConfig.java
> +			.addPathPatterns("/oauth/github/refresh/**");
Front와 협의하여 Refresh Token을 통해 요청(Token Reset)할 수 있는 API를 따로 만들기 위해 Interceptor로 분기 처리 했습니다.

2022-06-20 12:15 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/common/config/WebConfig.java
> +			.allowedOrigins("http://localhost:3000", "http://3.36.69.201");
Front 분들이 배포된 URL에서 테스트를 해볼 수 있게 하기 위해 CORS 문제를 해결하였습니다.

2022-06-20 12:16 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/application/OAuthService.java
> +		);
Controller에서 User domain 객체를 생성하지 않고, Service에서 생성하도록 refactoring 하였습니다.

2022-06-20 12:19 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/CommonInterceptor.java
> +}
AuthInterceptor(AccessToken전용)과 RefreshInterceptor가 공통적으로 갖는 로직을 추상클래스를 이용하여 대체 하였습니다.

2022-06-20 12:20 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
> -	private static final int EXPIRED_SECOND = 24 * 60 * 60;
Controller가 갖고있기보다 직접 쓰이는 `TokenType`이 관련 정보를 갖게 하였습니다.

2022-06-20 12:22 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
> +		return ResponseEntity.status(HttpStatus.OK)
응답 바디에 View에서 필요할 유저 정보를 담아 제공하기 위해 상태코드를 `MOVED_PERMANENTLY`에서 `OK`로 바꾸었습니다

2022-06-20 12:24 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
> +		User user = (User) request.getAttribute("user");
User가 쓰이는 곳마다 DTO를 받아온 것을 다시 조회하게 하는 것이 불필요한 과정처럼 느껴졌습니다. 
그래서 Interceptor를 거친 뒤 DTO가 아닌 User 엔티티를 가져오게 되는데, 이렇게 해도 되는 것인지 궁금합니다.
(Filter, Interceptor 같이 컨트롤러 직전에 거치는 로직에 대해서도 DTO 처리가 필요할까요?)

2022-06-20 12:24 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/user/infrastructure/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
지난 프로젝트에서 순수 JPA를 사용해 봤기 때문에 이번 프로젝트에서는 Spring Data JPA 를 사용해보고자 합니다.

2022-06-20 15:27 UTC, Hyune-c requested changes
수고하셨습니다.

2022-06-20 15:27 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/common/config/WebConfig.java
> +			.addPathPatterns("/oauth/github/refresh/**");
좋은 접근 입니다. 👍

2022-06-20 15:27 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/exception/ErrorCode.java
> +	UNAVAILABLE_TOKEN(HttpStatus.BAD_REQUEST, "Unavailable Token");
http status code에 대한 생각을 조금 더 해보시면 좋을 것 같습니다.

- 인증은 보통 401, 403으로 표현됩니다.
    - 뭉뚱그려서 표현한다는 것이죠. 왜일까요.
- 406이 인증 실패에 관련된 것인지 고민해보면 좋을 것 같습니다.

2022-06-20 15:27 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/application/JwtFactory.java
> +		cal.add(Calendar.SECOND, type.getTime());
좀 더 고민해주세요.
기능은 작동할지라도 안티패턴에 가까운 구현 중 하나입니다.

2022-06-20 15:27 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/GithubUser.java
> +	private String userSecret;
혹시 이게 뭔가요?
네이밍만으로 볼때는 굉장히 위험한 것 같습니다만..

secret이 노출 된다..?

2022-06-20 15:27 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/AuthInterceptor.java
> +		return claims;
굳이 Claims를 나눠야만 되나요?

2022-06-20 15:27 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
> +		User user = (User) request.getAttribute("user");
이건 구현 방법에 따라 다릅니다.
근데 저는 User 자체를 주고 받기보다는 id만 주고 받을 것 같아요.

2022-06-20 16:55 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/AuthInterceptor.java
> +		return claims;
- 바로 return을 하면 굳이 나눌 필요가 없을 것 같습니다!

```java
try {
        return JwtFactory.parseClaims(authorizationHeader.substring("Bearer " .length()));
} catch (ExpiredJwtException e) {
	throw new AuthException(ErrorCode.REFRESH_TOKEN_EXPIRED);
}
```

2022-06-20 17:04 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/GithubUser.java
> +	private String userSecret;
사실 `user Id`로 하려고 하다가, GitHub의 `user Id`가 변경이 가능하다는 사실을 알고나서 
불변하는 값들(`id`, `node_id`) 중에서 `node_id`를 선택해서 식별을 위해 사용하려고 했습니다
네이밍을 조금 더 심사숙고하고 정했어야 했는데, 그러지 못했던 것 같습니다 
조금 더 좋은 이름을 생각해보겠습니다!

2022-06-20 17:15 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
> +		User user = (User) request.getAttribute("user");
이와 관련하여 다른 팀 PR 리뷰하신 것을 보고 궁금한 점이 생겨 질문 남깁니다!
인터셉터를 통해 인증을 하게 되면, 불가피하게 request를 변경할 수 밖에 없다고 생각(like `id 값` 넘겨주기)을 했는데요
ArgumentResolver를 통해 user 정보를 넘겨주는 것 외에는 딱히 다른 방도가 생각이 나지 않았습니다.
혹시 다른 방법이 있는지 궁금합니다!

2022-06-20 17:22 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/GithubUser.java
> +	private String userSecret;
업무 내용 파악이 안되어 판단이 힘드네요.
주석을 활용해보시는 것을 추천합니다.

secreat라는 단어는 너무 위험해보이네요.

2022-06-21 00:59 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
> +		User user = (User) request.getAttribute("user");
감사합니다!

2022-06-21 01:00 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/GithubUser.java
> +	private String userSecret;
네 수정할 수 있도록 하겠습니다

2022-06-21 01:42 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/exception/ErrorCode.java
> +	UNAVAILABLE_TOKEN(HttpStatus.BAD_REQUEST, "Unavailable Token");
조금 섣부르게 상태코드를 정했던 것 같습니다!
406은 [서버주도 컨텐츠 협상](https://developer.mozilla.org/ko/docs/Web/HTTP/Content_negotiation#%EC%84%9C%EB%B2%84_%EC%A3%BC%EB%8F%84_%EC%BB%A8%ED%85%90%EC%B8%A0_%ED%98%91%EC%83%81)을 수행하고 나서 클라이언트 측에서 규격에 맞지 않게 컨텐츠 요청을 보냈을 때 이용하는 방식임을 알게 되었습니다.

- 401 : 미승인(unauthorized)으로 명시되어있으나 실질적으로 비인증(unauthenticated)을 의미하여 클라이언트 측에서 다시 요청을 해야하는 때에 사용하는 것으로 이해했습니다.

- 403 : 실질적으로 미승인(unauthorized)를 의미하여, 서버에서 클라이언트의 요청을 거절한다는 의미로 사용하는 것으로 이해했습니다.

2022-06-21 05:01 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/RefreshInterceptor.java
>  		}
네 감사합니다!!

2022-06-21 05:33 UTC, Hyune-c approved these changes
수고하셨습니다.

2022-06-21 05:34 UTC, merged