[Team24][BE] 민지노 && 필 2주차 첫번째 PR 요청드립니다.
codesquad-members-2022/issue-tracker pull request #116
Opened 2022-06-22 06:32 UTC by PhilSoGooood

안녕하세요 단! 필지노입니다! 
이번 한주도 잘부탁드립니다. 감사합니다.

### 수정 사항
- [x] DTO를 만들어줌에 따라 순환참조를 방지하기 위한 JSON 어노테이션을 삭제하고 FetchType을 Lazy로 수정하였습니다.
- [x] Soft Delete를 위해 이슈, 라벨, 마일스톤에 isDeleted 칼럼을 추가하였습니다.

### 구현 사항
- [x] 이슈, 라벨, 마일스톤 조회기능을 구현하였습니다.
- [x] 프론트 배포(CloudFront와 S3)

[API 명세서](https://documenter.getpostman.com/view/18134867/UzBmNnuF)

### 앞으로 진행 계획
- OAuth2.0을 이용한 로그인 기능
- 테스트 코드 작성

2022-06-22 10:56 UTC, Hyune-c requested changes
수고하셨습니다.

---

![image](https://user-images.githubusercontent.com/55722186/175012633-b67ad8d2-24bf-4d29-804d-055b83384713.png)

패키지 구조를 다시 생각해주세요.

2022-06-22 10:56 UTC, Hyune-c commented on BE/src/main/java/team24/issuetracker/domain/Label.java
> +    private boolean isDeleted;
`nit`
`is`는 질문/행위에 더 어울린다고 생각합니다.
지금의 상태라면 Labael의 삭제여부를 확인하기 위해 `getIsDeleted()`를 사용해야 될 것 같습니다.

2022-06-22 10:56 UTC, Hyune-c commented on BE/src/main/java/team24/issuetracker/web/controller/IssueController.java
> +	}
API 설계에 대해 다시 고민해보셔야 될 것 같습니다.

- path에 id가 들어가는 것은 암묵적으로 리소스의 id를 말합니다.
    - 하지만 로직을 보니 userId인 것 같습니다.
- create, assigned, commented는 조회 조건이라고 생각됩니다.

2022-06-22 10:56 UTC, Hyune-c commented on BE/src/main/java/team24/issuetracker/web/controller/IssueController.java
> +		return issueService.findIssuesCreatedByMe(id);
실수로 다른 사람 id를 넣으면 어떻게 되나요?
- 메서드명에 `Me`가 들어가 있네요.

2022-06-22 10:56 UTC, Hyune-c commented on BE/src/main/java/team24/issuetracker/web/repository/IssueRepository.java
> +	@Query("select i from Issue i where i.isClosed = :isClosed and i.isDeleted = false")
`nit` 네이티브 쿼리를 쓴다면 개행을 넣는 것을 추천합니다. + 가독성

2022-06-22 10:56 UTC, Hyune-c commented on BE/src/main/java/team24/issuetracker/web/service/MilestoneService.java
> +	}
```java
return milestoneRepository.findAll().stream().parallel()
		.map(milestone -> {
			final List<Issue> issues = milestone.getIssues();
			return new MilestoneListResponse(milestone, issues.size(), issues.stream().filter(Issue::isClosed).count());
		})
		.collect(Collectors.toList());
```

`nit`
foreach문을 줄이고 병렬 처리 하는 정도를 할 수 있을 것 같습니다.
하지만 전 지금도 충분히 괜찮다고 생각합니다.
- `milestoneRepository.findAll()`할 때 정렬을 안하셨기에 병렬 처리를 언급했습니다.
- 순서가 의미가 있다면 병렬 처리해서는 안됩니다.

2022-06-23 03:09 UTC, Minzino commented on BE/src/main/java/team24/issuetracker/domain/Label.java
> +    private boolean isDeleted;
현재 변수명이 isDeleted인데 @Getter를 사용하면 메서드명은 getIsDeleted() 맞는것 아닌가용? 🤔

2022-06-23 03:11 UTC, Minzino commented on BE/src/main/java/team24/issuetracker/web/controller/IssueController.java
> +	}
id가 아니라 userId 이렇게 명시적으로 나타내라는 말씀이신가요?

2022-06-23 04:57 UTC, Hyune-c commented on BE/src/main/java/team24/issuetracker/domain/Label.java
> +    private boolean isDeleted;
네. 지금의 구성이라면 그렇게 될 수밖에 없습니다. 
힌트를 좀 더 드리자면, 변수명에서 is를 빼면 어떨까요.

2022-06-23 04:59 UTC, Hyune-c commented on BE/src/main/java/team24/issuetracker/web/controller/IssueController.java
> +	}
네. 지금의 구조라면 id는 `issueId`로 읽힙니다.
하지만 `userId`가 로직임으로 명시하는 것이 좋다고 생각합니다.

2022-06-23 04:59 UTC, Hyune-c commented on BE/src/main/java/team24/issuetracker/web/controller/IssueController.java
> +		return issueService.findIssuesCreatedByMe(id);
어.. 메서드명을 바꾼다고 해서 id를 잘못넣는 이슈가 발생하지 않는 것은 아니지 않나요?

2022-06-23 05:02 UTC, Hyune-c approved these changes
일부 대화가 필요한 것이 있지만 크리티컬하지 않음으로 approve합니다.
수고하셨습니다.

2022-06-23 05:17 UTC, merged