[Team03] 이슈 관리 프로젝트 1주차 1차 PR 요청입니다.
codesquad-members-2022/issue-tracker pull request #13
Opened 2022-06-15 07:51 UTC by naneun

## 인사

안녕하세요 로치!
이슈 관리 프로젝트를 진행 중인 백엔드 팀 `BC`, `리아코` 입니다!
마지막 프로젝트 리뷰어로 로치를 뵙게 되어 영광입니다 😂
열심히 해보도록 하겠습니다!
감사합니다! 😄

## 한 일

- [x] 요구사항을 PDF 로 정리
- [x] 요구사항을 분석하며 테스트 코드 작성
- [x] 작성한 테스트 코드를 기반으로 엔티티 설계

2022-06-15 08:49 UTC, tmdgusya requested changes
고생하셨습니다. 코드가 짧고 간결해서 좋네요.
몇가지만 생각해보시고, 수정하시고 넘어가시죠

2022-06-15 08:49 UTC, tmdgusya commented on README.md
> +  - chore: 빌드 업무 수정, 패키지 매니저 수정 (ex .gitignore 수정 같은 경우)
👍

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/java/com/team03/issuetracker/issue/domain/Comment.java
> +	}
객체에 걸맞는 메소드 이름이네요. 👍

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/java/com/team03/issuetracker/issue/domain/Issue.java
> +    @CreatedBy
이런 기능도 아시는 군요. 👍

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/java/com/team03/issuetracker/issue/domain/Label.java
> +		}
이렇게 코드를 적는것도 좋은데 차라리 RequestDTO 자체에서 Validation 을 하는게 좋아보여요.
그렇다면 여기서는 null 이 아닐수 있지 않을까요?

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/java/com/team03/issuetracker/milestone/domain/Milestone.java
> +		}
요것도 위에 언급드린것과 마찬가지입니다~!

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/java/com/team03/issuetracker/milestone/domain/Milestone.java
> +	private List<Issue> issues = new ArrayList<>();
재 할당 될일이 없다면 final 을 붙여주세요.

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/java/com/team03/issuetracker/milestone/repository/MilestoneRepository.java
> +	MilestoneRepositoryCustom {
interface 를 한가지로 쓰시는 방법을 택하셨군요. 저도 좋은것같아요 ㅎㅎ

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/java/com/team03/issuetracker/milestone/repository/custom/MilestoneRepositoryImpl.java
> +				select(issue.count()).from(issue).where(issue.state.eq(CLOSE))))
아하 카운트를 세기위해서 SubQuery 를 쓰시는 군요. 
성능상 괜찮은지 확인해보셨나요. 만약 모르겠다면 답장안해주셔도 되요. 천천히 공부해도 되는 지식이니까요.

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/java/com/team03/issuetracker/issue/repository/EmojiRepository.java
> +public interface EmojiRepository extends JpaRepository<Emoji, Long> {
요건 공부해보면 좋은 내용인데 혹시 `CRUDRepository` 와 `JPARepository` 의 차이를 아시나요?

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/java/com/team03/issuetracker/issue/repository/EmojiRepository.java
> +public interface EmojiRepository extends JpaRepository<Emoji, Long> {
만약 EmojiRepository 가 `CRUDRepository` 정도로도 충분한 것 같으면 Type 을 바꿔주어도 좋을 것 같아요.

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/resources/application.yml
> +        enabled: true
이거 쓰시는 이유가 있나요? 프론트엔드에서 form 으로 PUT / DELETE 를 날리나요?

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/main/resources/application.yml
> +          batch_size: 1000
이건 나중에 공부해보면 좋은데 JPA 에서 AutoIncrement 를 모든 Entity 가 사용하고 있는 상황에서 bulk insert 가 작동할까요?

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/test/java/com/team03/issuetracker/issue/repository/CommentRepositoryTest.java
> +    @Transactional
`@Transationcal` 은 test 환경에서 어떻게 작동할까요?

2022-06-15 08:49 UTC, tmdgusya commented on backend/src/test/java/com/team03/issuetracker/issue/repository/CommentRepositoryTest.java
> +                .orElseThrow(CommentException::new);
저는 `when` 을 가리키는 행위가 두가지 있는 것은 좋지 않은 코드라고 생각을 해요.

given, when, then 에서 then 절의 when 에서 일어났던 행위에 대한 결과를 평가하는 것인데, 지금 when 절의 행위가 복수인 상태죠. 따라서 save 를 given 절로 올리거나, 아니라면 두 메소드가 하나의 행위인데, function 으로 묶여있지 않다. 라고 해석 될것 같아요.

2022-06-16 01:34 UTC, naneun commented on backend/src/test/java/com/team03/issuetracker/issue/repository/CommentRepositoryTest.java
> +                .orElseThrow(CommentException::new);
ㅎㅎ 이런 부분도 봐주시고 감사드립니다! 로치~ 다시 보니까 정말 어색하네요. 말씀 주신 방향으로 수정했습니다! 😂

2022-06-16 01:37 UTC, naneun commented on backend/src/main/resources/application.yml
> +        enabled: true
네! 안드로이드 팀분들이 PATCH / DELETE 메서드를 사용해도 괜찮다고 하셔서 API 를 좀 더 세부적으로 표현하는 방향으로 진행하려고 합니다! 😁

2022-06-16 01:39 UTC, naneun commented on backend/src/main/java/com/team03/issuetracker/issue/domain/Issue.java
> +    @CreatedBy
로그인 기능을 구현하고 연계해야하는 부분이라 학습하면서 방향을 고민 중 입니다! ㅎㅎ

2022-06-16 01:41 UTC, naneun commented on backend/src/main/java/com/team03/issuetracker/issue/domain/Comment.java
> +	}
ㅎㅎ 감사합니다! 😄

2022-06-16 01:57 UTC, honeySleepr commented on backend/src/main/java/com/team03/issuetracker/milestone/repository/custom/MilestoneRepositoryImpl.java
> +				select(issue.count()).from(issue).where(issue.state.eq(CLOSE))))
성능 테스트는 못해봤지만 한 요청에 쿼리가 여러 번 나가는 건 좋지 않을 것 같습니다. 그래서 쿼리가 한 번만 나가도록  Milestone 엔티티를 통째로 조회한 다음에 서비스단에서 카운트를 분리하는 방법으로 변경해 보려 합니다!

2022-06-16 01:57 UTC, honeySleepr commented on backend/src/main/java/com/team03/issuetracker/milestone/domain/Milestone.java
> +	private List<Issue> issues = new ArrayList<>();
넵!

2022-06-16 01:57 UTC, honeySleepr commented on backend/src/main/java/com/team03/issuetracker/milestone/domain/Milestone.java
> +		}
넵 적용하겠습니다!

2022-06-16 01:57 UTC, honeySleepr commented on backend/src/main/java/com/team03/issuetracker/issue/domain/Label.java
> +		}
넵! 수정 요청에 대한 validation 책임은 DTO가 가지도록 하겠습니다

2022-06-16 01:58 UTC, honeySleepr commented on README.md
> +  - chore: 빌드 업무 수정, 패키지 매니저 수정 (ex .gitignore 수정 같은 경우)
(처음엔 이렇게 하기로 정했었으나 Gitmoji를 쓰는 걸로 급변경하게 되었습니다😅)

2022-06-16 12:22 UTC, naneun commented on backend/src/test/java/com/team03/issuetracker/issue/repository/CommentRepositoryTest.java
> +    @Transactional
테스트 메서드가 종료되면 생성했던 데이터를 rollback 합니다. 다만 @DataJpaTest 어노테이션에 @Transactional 이 포함되어있어 불필요하게 메서드 레벨에서 또 다시 작성해줄 필요가 없었네요 😅 JpaRepository 기능을 테스트하기 위한 용도로 사용했고 서비스 테스트 코드 작성 시에는 사용하지 않을 예정입니다!

2022-06-16 12:27 UTC, honeySleepr commented on backend/src/main/java/com/team03/issuetracker/issue/repository/EmojiRepository.java
> +public interface EmojiRepository extends JpaRepository<Emoji, Long> {
`CrudRepository는` 기본 CRUD 기능을 제공하고 findAll() 메소드가 Iterator를 반환합니다.
`JpaRepository`는 여기에  paging과 sorting 기능이 추가된 거였군요!  Emoji의 경우 말씀해 주신대로 단순 조회만 하면 돼서 CrudRepository를 쓰도록 하겠습니다🙏

2022-06-16 12:49 UTC, honeySleepr commented on backend/src/main/resources/application.yml
> +          batch_size: 1000
hibernate는 쿼리를 모아놨다가 한 번에 요청하게 되는데, auto_increment의 경우 DB에 데이터가 insert 되면서 id가 지정되기 때문에 bulk insert 시 문제가 생기는 것으로 이해하였습니다!

2022-06-17 10:24 UTC, merged

2022-06-17 10:24 UTC, tmdgusya commented
고생하셨습니다