[team-23(BE)] IssueTracker - 레이블, 마일스톤 API 기능 구현, 이슈 저장로직 수정
codesquad-members-2022/issue-tracker pull request #173
Opened 2022-06-24 03:05 UTC by ak2j38

## 2주차 2번째 PR
- dan😁 안녕하세요! 로니와 아더입니다. 
- 2주차 두 번째 PR을 보냅니다! 
- 남은 기간도 잘 부탁드립니다! 
- 이번에 서버 배포쪽에서 이슈가 생겨 많은 시간을 소비해 작성한 코드가 많이 없고 리뷰주신 내용도 많이 반영하지 못했습니다. 😅

## 진행 사항

### 1.  레이블, 마일스톤 API 기능 구현
  - 목록, 등록, 수정, 삭제 기능 구현
  - 엔티티 맵핑 중 `cascadeType, orphanRemoval` 속성을 추가하였습니다. 

### 2. 이슈 저장 로직 수정
  - 반환형 `Long id`로 반환되도록 수정했습니다.
  - queryDSL 수정 및 이슈 필터링 DTO에 각 객체들이 들어올 수 있도록 수정했습니다.

## 질문 사항
  - 코드상에 코멘트 남겨두겠습니다!

2022-06-24 08:27 UTC, Hyune-c requested changes
컨플릭트가 있는 것 같아요.
수정하고 다시 올려주세요.

2022-06-24 13:03 UTC, Hyune-c requested changes
수고하셨습니다.

---

domain 패키지에 repository가 있고, service 패키지는 따로 분리되어 있네요?
의도가 궁금합니다.

2022-06-24 13:03 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/LoginArgumentResolver.java
> +        return authService.extractUserIdByToken(token);
`nit` 
네이밍을 고민하고 계시군요. 좋은 접근입니다.
- `extractUserIdFromToken`은 어떨까요.
- 나아가 `FromToken`도 뺄 수 있는 방법을 생각해보면 좋을 것 같습니다.

2022-06-24 13:03 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/AuthController.java
> +    public LoginResponse requestAccessToken(String code) {
- `/auth/github` `requestAccessToken` `LoginResponse`

url은 github 인증을 말하고, 메서드명은 accessToken을 달라고 말하고, 반환형은 Login을 말하고 있네요.
문맥은 이해가 되지만 좀 더 다듬을 수 있을 것 같습니다.

2022-06-24 13:03 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/IssueController.java
> +    * */
이것은 TODO 성격의 주석인 것 같습니다.

2022-06-24 13:03 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/IssueController.java
> +    public IssueDetailResponse showIssue(@PathVariable Long issueNumber) {
show라는 표현은 오랜만이네요.
어떤 의도를 가지고 네이밍 한 것인가요?

2022-06-24 13:03 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/IssueController.java
> +        return new IssuesResponse(countByStatus, issues.getTotalElements(), issues);
`openStatus가 왜 부정형으로 쓰였지?`가 바로 이해 안됬는데 로직을 보니 이해가 되네요..
- openStatus와 관계 없이 Issue를 모두 조회하면 좀 더 간결해지지 않을까요?

2022-06-24 13:03 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/LabelController.java
> +    }
`nit`
```suggestion
    @ResponseStatus(HttpStatus.NO_CONTENT)
    @DeleteMapping("/labels/{id}")
    public void delete(@PathVariable final Long id) {
        labelService.deleteById(id);
    }
```

2022-06-24 13:03 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueCondition.java
> +    }
`ofFor`는 좀 어색한 느낌인데 어떤 의도인가요?

2022-06-24 13:03 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/domain/milestone/Milestone.java
> +    private LocalDate endDate;
👍

2022-06-24 13:03 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/service/LabelService.java
> +        labelRepository.deleteById(id);
어짜피 지울건데 `findById`가 필요한가요?

2022-06-25 13:30 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/controller/IssueController.java
> +    public IssueDetailResponse showIssue(@PathVariable Long issueNumber) {
단순히 이슈목록을 보여주는 API라고 생각해서 `show`라는 접두사를 붙였는데 의도가 애매해 보일 수 있어 다른 좋은 단어를 고민해보겠습니다!

2022-06-25 13:36 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/controller/IssueController.java
> +        return new IssuesResponse(countByStatus, issues.getTotalElements(), issues);
DB단에서 가져올때부터 페이징을 처리하기 위해 `openStatus` 별로 조회해오는 로직을 구성했습니다.

말씀해주신대로 `openStatus`와 상관없이 `Issue`를 모두 가져온다고 가정했을 때 저희가 우려했던 부분은 데이터가 많을 경우 불필요한 데이터들까지 조회해와서 필터링하는 로직이 들어가 성능상의 문제와 요구되는 페이징 사이즈를 맞추기 어려울 것으로 판단했습니다. 😅

2022-06-25 13:38 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/controller/LabelController.java
> +    }
`ResponseEntity` 대신에 `@ResponseStatus`를 적극적으로 활용하겠습니다!

2022-06-25 13:43 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/controller/AuthController.java
> +    public LoginResponse requestAccessToken(String code) {
수정하면서 생긴 메서드명과 반환타입에 대해서 조금 더 명확하게 나타낼 수 있도록 더 고민하겠습니다! 👍

2022-06-25 13:43 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueCondition.java
> +    }
처음에 의도했던 바는 여러 개의 정적 팩토리 메소드가 생길 것이라고 판단하여 각 정적 팩토리 메소드 네이밍에 의미를 부여하려 했으나 다시 로직을 점검한 결과 하나의 정적 팩토리 메소드로 처리 가능할 것으로 보여 수정하도록 하겠습니다.

또한 이런 경우에는 정적 팩토리 메소드의 컨벤션인 `of`에 다른 네이밍을 덧붙이는 것이 아닌 새로운 네이밍 메소드를 만드는 것이 더 낫다는 점을 학습했습니다. 🙇‍♂️

2022-06-25 13:46 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/service/LabelService.java
> +        labelRepository.deleteById(id);
존재하지 않는 `id`에 대하여 예외처리를 할 목적으로 `findById`를 수행했었습니다.

하지만 `deleteById` 내부를 살펴본 결과 잘못된 `id`가 들어오면 예외를 던져주는 것을 확인했고 `findById`를 제거하는 것으로 수정하는 방향으로 의논되었습니다. 감사합니다!

2022-06-25 14:04 UTC, CMSSKKK commented
> domain 패키지에 repository가 있고, service 패키지는 따로 분리되어 있네요?
 의도가 궁금합니다.

- 이전 프로젝트에서 MVC 구조로 패키지 구조도 사용해보고, 도메인별로 패키지 구조도 사용해본적이 있습니다. 
- 이번에는 저희가 편하게 찾을 수 있도록 새롭게 구성해보자라는 의도로 시작했지만..... MVC 구조와 도메인별 패키지 구조가 혼합되서 혼종이 된것 같습니다.. 
- 다시 명확하게 역할에 맞게 패키지구조를 수정하도록 하겠습니다.

> PR 이후에 꽤나 많은 수정이 생겨서 수정사항을 커밋하기 보다는, 리뷰 주신 내용 참고해서 다음 PR에 반영하도록 하겠습니다!

Q :  DDD 패키지 구조에서 추상화된 repository의 경우 domain 패키지 내에 두는 것으로 알고 있는데, JPA 레포지토리를 상속한 레포지토리의 경우는 기술에 의존적인것으로 보이는데.. Infrastructure 패키지 내에 두는 것이 맞을까요??

2022-06-25 21:42 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/IssueController.java
> +        return new IssuesResponse(countByStatus, issues.getTotalElements(), issues);
그렇네요. page를 고려하시면 지금이 맞습니다.
좀 더 좋은 방법이 있을 것 같은 느낌인데 딱 떠오르지가 않네요..

2022-06-25 21:49 UTC, Hyune-c commented
> Q : DDD 패키지 구조에서 추상화된 repository의 경우 domain 패키지 내에 두는 것으로 알고 있는데, JPA 레포지토리를 상속한 레포지토리의 경우는 기술에 의존적인것으로 보이는데.. Infrastructure 패키지 내에 두는 것이 맞을까요??

이건 사람마다 해석이 틀려요.
교체 가능 기술이라고 판단하면 `infrastructure`에 넣을 것이고, 그렇지 않다고 판단하면 `domain` 영역에 둡니다.

저는 개인적으로 spring이나 jpa가 교체할 일이 있을까.........
라는 생각으로 모듈로 분리하는게 아닌 이상 domain 패키지에 넣습니다.
샘플로 최근 제가 편의성을 적당히 섞어 만든 패키지 구조를 공유합니다.

<img width="198" alt="image" src="https://user-images.githubusercontent.com/55722186/175791426-76e5d284-2c14-41c2-85f9-d27f3d9a91f2.png">

2022-06-27 00:41 UTC, merged