[TEAM-25][BE] 2주차 PR
codesquad-members-2022/issue-tracker pull request #180
Opened 2022-06-24 04:49 UTC by fpzk5656

안녕하세요?브라이언!
2주차 PR 요청 보냅니다.

슬럼프가 와서 코딩을 많이 못했습니다.
죄송합니다.

언제나 훌륭한 리뷰 감사드립니다

2022-06-24 15:04 UTC, wheejuni requested changes
코드에도 슬럼프가 찾아온 것이 티가 나는군요. 우선 고생 많으셨습니다. 💯 
코딩을 공부하는 것도 중요하지만 코딩 공부를 하는 법을 공부하는 것도 중요합니다. 중요한 시기에 슬럼프가 왔다는 것은 뭔가 재점검과 재정비가 필요하다는 신호로서 받아들이시고, 빠르게 슬럼프를 탈춣해 다시 페이스를 올릴 방법을 찾아보시는 것이 좋겠습니다.
필요하다면 호눅스, 클로이 등 도움을 줄 수 있는 분들에게 도움을 구하시기 바랍니다.

지금 드린 코멘트들 이외에도 말하고 싶은 것이 많지만, 정상적인 컨디션 하에 작성한 코드가 아니라는 생각에 말을 줄였습니다. 우선 일곱가지 코멘트만 읽고 고민해주세요.

2022-06-24 15:04 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/JwtTokenProvider.java
> +			return null;
`return null` 이라면 `Optional<String>` 으로 처리해보시는 건 어때요?

2022-06-24 15:04 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/JwtTokenProvider.java
> +			//refresh 토큰이 만료되었을 경우, 로그인이 필요합니다.
전반적으로 스페이스와 개행이 컨벤션에 많이 맞지 않습니다. 한번만 체크를...

2022-06-24 15:04 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/JwtTokenProvider.java
> +	public String recreationAccessToken(String userEmail, Object roles){
`roles` 의 타입을 구체화하긴 어려운 걸까요.

2022-06-24 15:04 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/JwtTokenProvider.java
> +			.setExpiration(new Date(now.getTime() + accessTokenValidityInMilliseconds)) // set Expire Time
`access...seconds` 는 상수인 것 같은데 네이밍이 컨벤션에 맞지 않아 보입니다만..

2022-06-24 15:04 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/controller/OauthRestController.java
> +	public ResponseEntity<ResponseLogin> login(@PathVariable String provider,
`LoginResponse` 가 더 적절한 클래스명일 것 같긴 합니다.

2022-06-24 15:04 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/controller/OauthRestController.java
> +		if (map.get("status").equals("402")) {
`status` 가 없다면 어떻게 될지 궁금하군요.
이런 목적이라면 클래스가 하나 더 설계되었어야 한다고 보는데요.

2022-06-24 15:04 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/controller/ResponseTokenMessage.java
> +	}
아래와 같은 이유로 이런 방식의 생성자는 별로 동의되지 않습니다.

- `map` 에 뭐가 들어올지 모르는데, 정해진 규칙이 있는 것처럼 작동하고 있습니다.
- `Builder` 라는 아주 좋은 대안이 있습니다.

그리고 클래스의 설계에 대해선 아래와 같은 의견을 드립니다.

- `String` 이면 위험할 필드들이 있다. `errorType`, `status` 와 같은 필드들은 문자열로 보관하기에 적절하지 않습니다.
- getter 없는데 어떻게 각 필드에 접근할지 궁금하다.

2022-06-27 17:19 UTC, fpzk5656 commented on BE/src/main/java/team25/issuetracker/JwtTokenProvider.java
> +			return null;
`return Optional.of(recreationAccessToken(claims.getBody().get("sub").toString(),
				claims.getBody().get("roles")))
			.filter(v -> !claims.getBody().getExpiration().before(new Date())).orElse(null);`
try catch를 없애고 위와 같이 반환하도록 변경해보았습니다.

2022-06-27 17:21 UTC, fpzk5656 commented on BE/src/main/java/team25/issuetracker/JwtTokenProvider.java
> +			//refresh 토큰이 만료되었을 경우, 로그인이 필요합니다.
😭

2022-06-27 19:29 UTC, fpzk5656 commented on BE/src/main/java/team25/issuetracker/controller/ResponseTokenMessage.java
> +	}
확실히 그렇네요..!
map을 쓸 필요도 없게
서비스단에서 사용할 DTO를 만들어서 
각각 key에 해당하는 필드들을 만들었습니다.
그리고 `status는 HttpStatus` , `errorType은 HttpClientErrorException` 라이브러리 객체들로 지정하여 String을 대체하였습니다.
좀만 더 손 본 후에 올리겠습니다

2022-06-28 13:54 UTC, fpzk5656 commented on BE/src/main/java/team25/issuetracker/JwtTokenProvider.java
> +	public String recreationAccessToken(String userEmail, Object roles){
역할에 대해 많이 찾아보고 생각해봤는데 굳이 해당 코드에서 roles를 굳이 받을 필요가 있나 싶어서
`Role` 객체로 Member가 셋팅값을 지니고 있음으로
저 상황에서 roles관련 코드는 삭제했습니다.

하지만 만약 프로젝트 진행하다 필수요소라면,
userEmail로 MemberRepository에서 조회해서 해당 멤버의 `Role`객체 필드를 직접 가져오는 방법을 쓸 예정입니다.

2022-06-28 14:58 UTC, wheejuni commented
@fpzk5656 ㅎㅎ 아직 작업중이실까요

2022-06-28 15:15 UTC, fpzk5656 commented on BE/src/main/java/team25/issuetracker/JwtTokenProvider.java
> +			.setExpiration(new Date(now.getTime() + accessTokenValidityInMilliseconds)) // set Expire Time
> @fpzk5656 ㅎㅎ 아직 작업중이실까요

아 곧 푸쉬 하겠습니다 ㅠ

2022-06-28 15:19 UTC, fpzk5656 commented
> @fpzk5656 ㅎㅎ 아직 작업중이실까요

지금 변경사항 푸쉬 했습니다!

2022-07-01 05:18 UTC, merged