[team-07] [Hwi & 땃쥐] issuetracker 4차 PR
codesquad-members-2022/issue-tracker pull request #194
Opened 2022-06-24 06:56 UTC by ttasjwi

안녕하세요 디온, 땃쥐 & 휘입니다!!
주문하신 스파게티가 나왔습니닷...!!!
주문이 늦어져서 죄송합니다ㅠㅠ 대신 미트볼을 추가해드렸습니다...:sob::sob::sob:

---

## 💻 주요 작업 내역

+ 이슈 생성 리팩토링
+ 이슈 수정
+ 이슈 다중상태 변경 최적화 : 쿼리 한번으로 하도록 함
+ 라벨 등록
+ 등록 시간과 수정 시간을 자동 갱신
+ 상세 조회 최적화

---

### 생성, 수정시각 공통화
![image](https://user-images.githubusercontent.com/88282356/175479489-b12d5631-15da-405b-b18c-a27f2cd0b30f.png)
- JPA Auditing을 활용하여 생성시각, 날짜를 공통화 처리했습니다.

---

### 상세조회 최적화
```java=
    @Override
    public Optional<IssueDetailResponse> findIssueDetail(Long issueId) {

        IssueDetailResponse issueDetailResponse = getIssueDetailResponse(issueId);

        if (issueDetailResponse == null) {
            return Optional.empty();
        }

        List<IssueDetailResponse.IssueAssigneeDto> assigneeDtos = findIssueAssigneeDtos(issueId);
        List<LabelDto> labelDtos = findLabelDtos(issueId);
        List<IssueDetailResponse.CommentListElement> commentDtos = findCommentDtos(issueId);

        issueDetailResponse.getAssignees().addAll(assigneeDtos);
        issueDetailResponse.getLabels().addAll(labelDtos);
        issueDetailResponse.getComments().addAll(commentDtos);

        return Optional.of(issueDetailResponse);
    }
```
- `IssueRepositoryImpl`에서 이슈 상세 DTO를 바로 조회하도록 함

---

## 지난번 PR
- 시간 관계상 모든걸 반영하지는 못 했습니다. ㅜㅜ
- 당장 디온이 말씀 주셨던 상세조회 부분을 다시 보니 매우 심각한 느낌이 들었습니다. 이 부분을 중점으로 했습니다.

---

## 다음에 할 것
- 마저 못 한 기능 구현
- OAuth/JWT
    - 우선순위 매우 높음. 이번에 학습하고 싶었는데 자꾸 미뤄서 아쉬웠어요. 좀 힘들고 시행착오가 있을 수 있겠지만 이번 김에 제대로 배워보고 싶습니다..)
- 예외처리
    - ExceptionHandler, Exception 메시지 공통화 처리
- 인터셉터 처리
  - 해당 요청에 대해 사용자가 접근 권한이 있는지 컨트롤러 접근 전에 판단하는 로직 (JWT, OAuth 선행 필요)
- 테스트 : 그동안 시간을 핑계로 테스트를 너무 미뤘습니다... 다음 주 수료식 일정 등등으로 인해 이 부분까지 할 수 있으리란 보장이 없긴 합니다. ㅜㅜ

2022-06-24 16:40 UTC, ksundong requested changes
안녕하세요. 땃쥐 & 휘, 리뷰어 dion입니다.
미트볼을 추가했다는건 좋은 의미는 아닌데 말이죠 ㅋㅋㅋㅋㅋㅋㅋ

여러분의 코드는 스파게티정도는 아닙니다 ㅎㅎ

## 조언

- OAuth/JWT 꼭 해보세요.
- 예외처리는 굳이..? 싶긴 합니다. 나중에 해보셔도 돼요.
- 인터셉터도 꼭 해보세요.
- 테스트는 **무조건** 해보세요.

## 리뷰 요약

- `private` 메서드의 과도한 사용이 눈에 띕니다.
- 제 리뷰를 잘못 해석하고, 잘못 구현한 부분도 있는 것 같아요. 이전 PR 코멘트 참고해주세요.

고생하셨습니다. 이번에도 마찬가지로 일요일 9시에 머지할 예정입니다.
리뷰드린 내용 반영가능하신 곳 까지 반영해주세요.

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/Comment.java
>      }
점점 생성자가 관리하는 필드가 적어지는군요. 의도한건가요?

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +        List<IssueAssignee> newAssignees = createNewAssignees(changeMembers);
이런식으로 private 메서드로 쪼개는건 좋은 방식이 아닙니다.
왜 안좋을까요?

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +     */
이런 주석은 거의 의미가 없습니다. 메서드 이름만 봐도 알 수 있습니다.
차라리 사용법을 적는게 낫죠.

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +    }
예전에 리뷰해드린게 기억이 나실진 모르겠는데, `private` 메서드는 사용되는 `public` 메서드 아래에 위치시켜주는게 가독성에 좋습니다.

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +    }
비슷한 코드죠? 메서드로 추출할건 이 메서드가 아니라 다른게 아닐까요?

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +    }
👍

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
> +    IssueAssignee(Member member, Issue issue) {
왜 접근 제어자를 없애는 선택을 해주셨나요?

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/repository/issue/IssueRepositoryImpl.java
> +    public Optional<Issue> findByIdWithAuthorAndMilestone(Long issueId) {
이름 잘 지어주셨네용

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/repository/issue/IssueRepositoryImpl.java
> +    }
별로 좋은 형태는 아닌 것 같군요. 작성하시면서 어떤 느낌같은게 오진 않았나요?
`Repository` 의 목적은 무엇일까요?

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueCommandService.java
> +        Milestone updateMilestone = findMilestone(updateRequest.getMilestoneId());
`issueCommandService`인데, `milestone` 을 조회하는 메서드가 있네요. 뭔가 의아하지 않나요?

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueDetailResponse.java
> +    private final List<CommentListElement> comments = new ArrayList<>();
저는 응답객체에는 `final` 을 붙여주는걸 권장합니다.
가급적이면 `final` 이 가능한 구간에는 다 붙여주세요.

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueDetailResponse.java
> +    }
보통 이런경우 nested class는 권장하지 않습니다. 경험상 재사용이 되어서 분리되는 경우가 잦아서 그냥 별도 클래스로 쪼개는게 나은 것 같아요.

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueDetailResponse.java
> +    }
얘는 왜 getter를 직접 만들어주셨나요...?

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/web/dto/label/LabelCreateRequest.java
> +    private String colorCode;
`ArgumentResolver` 를 이용하면 좋지 않을까요?

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/web/IssueController.java
> +        return new IssueStateChangeResponse(issueId, isOpened);
왜 이렇게 해줘야 하나요..?

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/web/IssueController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
`NO_CONTENT` 가 맞나요?

2022-06-24 16:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/web/LabelController.java
> +        Label label = labelCreateRequest.toEntity();
왜 여기서 `Entity` 로 만들게끔 해주셨나요?

2022-06-24 22:09 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueDetailResponse.java
> +    }
boolean isOpened는 `@getter`로 getter생성시 isOpened로 getter가 생성되는 바람에 이렇게 처리했습니다.

2022-06-24 22:12 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/Comment.java
>      }
auditing으로 생성일자 수정일자를 자동 갱신해주기에 엔티티 코드에서 직접 관리하지 않도록 했습니다.

2022-06-24 22:16 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueCommandService.java
> +        Milestone updateMilestone = findMilestone(updateRequest.getMilestoneId());
조회를 다른 서비스를 통해 하는건 어떻게 생각하시나요?

2022-06-25 05:10 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +        List<IssueAssignee> newAssignees = createNewAssignees(changeMembers);
저희는 외부에서 changeIssueAssignees 메서드만 알게 하면 된다고 생각했고, 그 내부 로직은 외부에서 굳이 알게 할 필요가 없다고 생각해서 저 메서드들을 private로 만들었는데요.

디온의 의견을 듣고 이 구조의 문제가 무엇일까 논의해봤을 때, 저희는 이렇게 했을 경우 "테스트의 단위가 너무 커지겠다"라는 결론을 내게 됐습니다. 이를 반영하게 된다면 private 메서드들을 public으로 공개하면

- 각각의 작은 메서드 단위로 테스트할 수 있다. 각각의 메서드별로 테스트가 더 쉬워지고, 기능의 신뢰성이 증가된다.
- 다만, 외부에서는 대신 기존에 changeAssignees를 호출하던 것을 잘게 자른 메서드들을 순서대로 호출하는 식으로 처리해야한다.

이런 결론을 낼 수 있었는데요. 디온이 생각하신 의도와 저희 생각이 비슷한 것인지 궁금합니다. 혹시 다른 의도셨다면 그 의도를 확인할 수 있을까요?

2022-06-25 05:12 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +    }
저희도 코드를 다시 확인해보니 기능구현에 급급하여 메서드 순서 조정을 나중으로 미룬 경우가 많았고 불만족스러운 것들을 몇 개 확인했는데, 이들과 더불어 다음 코드에서 반영하겠습니다!

2022-06-25 05:15 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +    }
필드의 변경에 set...을 두면 의미가 불분명하기 떄문에, 변경의 이유를 메서드 명에 표현하였습니다!

2022-06-25 05:17 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
> +    IssueAssignee(Member member, Issue issue) {
외부에서 Assignee를 생성하지 않게 하고 issue.changeIssueAssignees 메서드를 통해 이슈 할당자 생성, 부착을 처리하기 위해서 메서드를 감췄습니다. 이들의 생성은 Issue라는 도메인에 종속적이여서 Issue를 거쳐서만 생성될 수 있게 하고 싶었습니다.

2022-06-25 05:30 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/repository/issue/IssueRepositoryImpl.java
> +    public Optional<Issue> findByIdWithAuthorAndMilestone(Long issueId) {
무엇을 페치조인해오는 지 사용측에서 편할 것 같아서 이렇게 이름을 변경했습니다.

2022-06-25 09:27 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/web/LabelController.java
> +        Label label = labelCreateRequest.toEntity();
요청 파라미터를 기반으로 엔티티를 생성하고 서비스에서는 단순히 등록만 해주려고 했었습니다.
근데 생각해보면 이슈를 생성하는 로직을 굳이 컨트롤러단에서 몰라도 되고, 서비스에서 책임지면 되므로 서비스에게 이 책임을 이동시키도록 하겠습니다.

2022-06-25 09:28 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/web/IssueController.java
> +        return new IssueStateChangeResponse(issueId, isOpened);
변경 후 이슈 질의를 다시 할 필요가 있을까? 싶어서 요청의 값을 그대로 넣도록 변경했었습니다.

생각해보면, 실제 변경 이후 엔티티의 상태를 반환하는게 맞을것 같아서 다시 롤백시킬 예정입니다.

2022-06-26 05:15 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueCommandService.java
> +        Issue issue = issueQueryService.findIssueById(issueId);
Issue의 질의에 관한 부분은 QueryRepository에서 전부 맡도록 하고 CommandService가 해당 데이터 질의가 필요할 때는 QueryService에 요청하도록 했습니다.

2022-06-26 05:16 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueQueryService.java
> +    public Issue findIssueById(Long issueId) {
조회 실패가 일어났을 때, 예외가 발생되도록 하는 로직은 질의를 책임지는 서비스단에서 집중하여 처리하게 하고 나머지 계층은 꺼내진 엔티티를 사용하도록 했습니다.

2022-06-26 11:07 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/service/label/LabelCommandService.java
> +    public Long createLabel(LabelCreateRequest labelCreateRequest) {
웹 요청 Dto를 서비스의  파라미터로 넣는 형태가 옳은지는 약간 의문이긴 한데요.

이 방식을 실무에서 사용하는지 궁금하고... 만약 그렇게 안 쓰더라도
실무에서는 보통 파라미터가 복잡할 경우, 컨트롤러에서 이를 서비스 전용 DTO로 변환하고 인자로 넣어 사용하시는지 궁금합니다.

2022-06-26 11:08 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/web/LabelController.java
> +        Long labelId = labelCommandService.createLabel(labelCreateRequest);
commandService의 반환 타입은 절대 엔티티를 반환하지 않게 했습니다.
반환하더라도 식별자 값이나 간단한 primitive 타입(boolean, int)들을 반환하게 했습니다.

2022-06-26 11:10 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
> +    public IssueAssignee(Member member, Issue issue) {
디온의 말씀대로 객체 생성을 issue 안에서 하기보다 public으로 열어두고 외부에서 생성 뒤 issue에서 주입하는 식으로 처리해보니 장점이 더 많아진 것 같았습니다. 일단 객체를 생성해서 테스트가 가능하다는 것이 가장 핵심입니다. 테스트가 편한 코드를 작성하는게 중요하다는 것을 느꼈습니다.

2022-06-26 11:12 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/excption/InvalidIssueAssigneeAddException.java
> +public class InvalidIssueAssigneeAddException extends BusinessException {
다른 Issue에 할당된 IssueAssignee를 추가하려는 상황은 앞선 로직을 확인하면 일어날 수 없지만 예외를 정의했습니다.

2022-06-26 11:13 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
> +@EqualsAndHashCode(of = {"member", "issue"})
issueAssignee의 동등성을 회원, 이슈를 기준으로 하도록 정의했습니다.

2022-06-26 11:14 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +    private final Set<IssueAssignee> assignees = new HashSet<>();
이슈의 회원을 변경하다보면 중복회원을 넣지 말아야하는데...
이 기준을 어떻게 하다가 동등성을 재정의하고 set으로 관리하도록 변경했습니다.

2022-06-26 11:18 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +        assignees.add(issueAssignee);
set에 동등한 객체를 add를 실행했을 때 기존 것을 덮어쓰는지 아무 것도 하지 않는 지 테스트를 진행했는데, 동등한 중복객체를 삽입하면 삽입 자체를 안 하더라구요. 그래서 set 구조로 바꾸고 add를 하기로 했습니다.

2022-06-26 11:18 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/Comment.java
>      }
너무 JPA에 의존적인 코드가 되어가고 있진 않나요?

2022-06-26 11:18 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +        assignees.add(issueAssignee);
이에 대한 테스트 코드는 이후 커밋에 추가했습니다.

2022-06-26 11:26 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +        List<IssueAssignee> newAssignees = createNewAssignees(changeMembers);
네 의도와 전혀 다릅니다.

추출한 의도가 무엇인가요? 이건 외부에서 알지 못하게 하기 위한 추출과는 다르다고 보입니다.
오히려 로직을 블럭으로 나눠놓은 형태가 아닐까요?
그리고, 메서드는 기본적으로 동작을 숨깁니다. 코드를 읽는 다른 사람이 파악하는 것을 더 어렵게하죠.

그냥 로직을 public method 안에 두어도 충분합니다.

2022-06-26 11:28 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueCommandService.java
> +        Milestone updateMilestone = findMilestone(updateRequest.getMilestoneId());
땃쥐는 어떻게 생각하시나요?

2022-06-26 11:32 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueDetailResponse.java
> +    }
아하 그랬군요.
Lombok의 네이밍 원칙이 primitive boolean을 메서드명으로 알 수 있게하자여서 그런 것 같네요.

2022-06-26 11:40 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/service/label/LabelCommandService.java
> +    public Long createLabel(LabelCreateRequest labelCreateRequest) {
실무에서 쓰냐 안쓰냐는 별로 중요하지 않아요. 너무 실무중심으로 생각하는게 가장 큰 문제로보여요.
실무의 범위도 너무 넓을 뿐더러, 왜 그렇게 해야하는가가 '실무에서 그렇게 하니까'가 될 가능성이 너무 높아보입니다.
실무에선 모든게 가능합니다. getter setter 점철된 코드로 객체지향 없이 하는 것도 실무고, DDD에 기반한 설계에 TDD를 적용하는것도 가능합니다. 이런 질문은 '무의미한' 질문이 될 가능성이 높습니다.

질문을 정정해보죠.

> 저는 기존에 서비스에 Entity를 넘겨주도록 디자인 했는데요. 디온의 리뷰를 적용하고보니 웹 요청에 대한 DTO가 서비스의 파라미터가 되는 형태가 옳은지 의문이 듭니다.

그럼 제 답변은 이렇게 될겁니다.

왜 엔티티가 `Controller` layer에 등장해야 했나요? `Controller` 의 역할은 무엇인가요? 그리고 엔티티의 역할은 무엇인가요?

서비스의 재사용성을 생각하면, 서비스용 DTO로 변환해서 범용적으로 쓰이는 것이 더 맞을 것으로 보입니다. 아니면 도메인 객체를 도입하거나요.
다만, 우리가 지금 만드는 것은 엔드포인트가 한 곳인 서비스여서, 웹 컨트롤러의 DTO가 그대로 전달되어도 괜찮다고 봅니다.

2022-06-26 12:17 UTC, ksundong approved these changes
고생하셨습니다. 😊

2022-06-26 12:17 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +    private final Set<IssueAssignee> assignees = new HashSet<>();
네 잘해주셨어요.

2022-06-26 12:17 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
> +    }
이 코드는 잘 이해가 안가네요.

2022-06-26 12:17 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
> +@EqualsAndHashCode(of = {"member", "issue"})
왜 인지가 더 중요합니다. '왜' 인가요?

2022-06-26 12:17 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
> +@EqualsAndHashCode(of = {"member", "issue"})
이게 엔티티가 엔티티의 역할과 도메인의 역할을 둘 다 가져서 약간의 혼란이 올 수도 있습니다. ㅎㅎ

2022-06-26 12:17 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
> +    }
이 코드를 보면 문제를 알 수 있는데요.
member는 전혀 고려하지 않았습니다.

2022-06-26 12:17 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/repository/issue/IssueRepositoryImpl.java
> +    public void updateBulkStates(List<Long> issueIds, boolean isOpened) {
여기서 말하는 `state`가 뭔가요?

2022-06-26 12:17 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueCommandService.java
> +        issue.addIssueLabels(issueLabels);
만들고 추가하는 과정이 한 덩어리 일 수는 없나요?

2022-06-26 12:17 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueQueryService.java
> +    public Issue findIssueById(Long issueId) {
넵넵

2022-06-26 12:17 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueQueryService.java
> +        issueDetailResponse.getComments().addAll(commentDtos);
아직도 이렇게 해줘야 하는 이유는 잘 이해가 안되네요.

2022-06-26 12:17 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/web/IssueController.java
> +    @ResponseStatus(HttpStatus.OK)
이걸 써줄 필요가 있나요?

2022-06-26 12:17 UTC, ksundong commented on BE/src/test/java/com/codesquad/issuetracker/domain/IssueTest.java
> +    Label labelB = new Label("labelB", "widwdniw", LabelColor.create("AAAAAA"));
이렇게 자주 생성되는 테스트용 객체는 factory를 만들어주세요.

2022-06-26 12:17 UTC, ksundong commented on BE/src/test/java/com/codesquad/issuetracker/domain/IssueTest.java
> +        assertThat(findIssueAssignee).isSameAs(issueAssigneeA);
여러개의 `assertion` 은 `assertAll` 로 감싸주세요.

2022-06-26 12:19 UTC, merged

2022-06-26 12:22 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
> +@EqualsAndHashCode(of = {"member", "issue"})
정의 시 Issue의 참여자인 Issueassignee , issueLabel의 Set을 통한 중복 처리에서 편의성을 느껴서 재정의했습니다.이를 통한 장점이 너무 커서 이를 사용했습니다.

2022-06-26 12:33 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueCommandService.java
> +        Milestone updateMilestone = findMilestone(updateRequest.getMilestoneId());
어제 휘랑 고민하고 service간 의존관계를 부여해봤습니다.

이를 통해 얻을 수 있는 장점이 매우 많았습니다. 관련 엔티티의 조회를 관련 쿼리서비스에서 집중적으로 책임지고,  커맨드 서비스는 동일 쿼리서비스를 의존하게 하게 하였는데요. 각 사비스에서 레포지토리를 의존하게했을 때는 각 서비스에서 조회에 대한 비슷한 예외처리를 하는 코드를 계속 작성하는 문제가 있었고 전혀 관계없는 엔티티를 질의하는 문제가 있었습니다. 

서비스간 의존관계를 두니, 책임의 집중, 분리가 잘 되는 장점이 생겼습니다. 물론 잘못된 의존관계를 맺어주면 순환참조가 발생할 여지가 있으니 이를 주의해야합니다.

2022-06-26 12:36 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueCommandService.java
> +        Milestone updateMilestone = findMilestone(updateRequest.getMilestoneId());
그런데 이 부분에서 트랜잭션 중첩에 관한 개념을 학습해야겠다는 생각이 들었습니다. 학습할 거리를 많이 얻어가네요! 정말 감사합니다. 디온!

2022-06-26 12:37 UTC, ttasjwi commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueCommandService.java
> +        Milestone updateMilestone = findMilestone(updateRequest.getMilestoneId());
그런데 이 부분에서 트랜잭션 중첩에 관한 개념을 학습해야겠다는 생각이 들었습니다. 학습할 거리를 많이 얻어가네요! 정말 감사합니다. 디온!

2022-06-26 16:19 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueCommandService.java
> +        Milestone updateMilestone = findMilestone(updateRequest.getMilestoneId());
네 스스로 느끼시는게 중요합니다.
제가 이게 맞다 말해도, 맞지 않을 수 있습니다. 코딩은 그런겁니다.
타인의 의견에 의존하지 않고, 본인의 주관을 뚜렷이 가지고 가시고, 다른 사람과 의견이 부딪히면 긍정적으로 검토해보시면 됩니다.
스스로 생각해보는 연습을 많이 해보시면 좋겠습니다.

2022-06-26 16:20 UTC, ksundong commented on BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
> +@EqualsAndHashCode(of = {"member", "issue"})
ㅎㅎ 맞아요. 사실 편의성의 문제가 아니라, 도메인의 정의상 그게 맞지요.
다만, 이게 순수한 엔티티였다면 어땠을까요?

엔티티와 도메인의 정의를 잘 생각해보세요. 😊