[team-08][BE] 개발, 배포용 yml 분리, 환경 변수 사용, 리뷰 반영
codesquad-members-2022/issue-tracker pull request #209
Opened 2022-06-24 17:10 UTC by donggi-lee-bit

안녕하세요 디온!! 동기입니다 ㅎㅎ 수요일 이후로 OAuth Github 로그인 기능 구현을 마무리하고 배포해보았습니다.
그 과정에서 개발, 배포 환경을 따로 두어야했기에 develop.yml, prod.yml 파일을 만들어 환경을 분리하고 로컬과 서버에 환경 변수 설정을 했습니다!

혼자 프로젝트를 진행하면서 지금까지 페어에게 얼마나 의존적인 프로젝트를 진행했는지 매순간 느끼고 있습니다..
지금이라도 알아서 다행이라고 생각하면서요.. 하하하하

인터셉터 혹은 필터 같은 기능이 없는 반쪽짜리 OAuth 구현이지만 남은 시간이 얼마 없기에 앞으로는 issue tracker 관련 API 개발을 진행하고자 합니다. 

PR 보내고 확인해보니 실제로 개발된 내용은 거의 없는 것 같네요.. 허허
그래도 이번 리뷰도 잘 부탁드리겠습니다!! 항상 좋은 말씀 감사합니다 😆 😆

2022-06-24 17:25 UTC, ksundong commented
내일 중으로 리뷰하겠습니다~ 좋은 밤 되세요. 🌙

2022-06-25 02:00 UTC, ksundong requested changes
안녕하세요. 동기, 리뷰어 dion입니다.
리뷰 내용 반영하느라 고생하셨어요.

혼자 프로젝트를 해보는 경험도 매우 중요하죠. 스스로 많이 해보시면 좋을 것 같아요.
네 이제부터는 기능 구현에 집중해보시기 바랍니다.
스스로 만족스러운 OAuth는 나중에 만들어보시면 좋을 것 같네요.

PR 머지하기전에 빠진 파일들이 좀 많아서 이 부분 확인 부탁드립니다.
고생하셨습니다. 즐거운 주말 보내세요!

2022-06-25 02:00 UTC, ksundong commented on .gitignore
> -
이 파일은 왜 빠졌나요?

2022-06-25 02:00 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/controller/LoginController.java
> +    public ResponseEntity<Void> login() {
이건 `githubLogin`이 더 적절하지 않을까요?

2022-06-25 02:00 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/controller/LoginController.java
> +        @Value("${oauth.github.redirect-uri}")String redirectUri,
`github` 관련해서는 따로 처리하는 구간이 있는게 더 낫겠네요.

2022-06-25 02:00 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/controller/dto/AuthLoginDto.java
> +@RequiredArgsConstructor
`RequiredArgsConstructor` 는 잠재적인 위험을 내포하고 있는데요. 혹시 알고 사용하고 계실까요?

2022-06-25 02:00 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/dto/GithubUser.java
> +public class GithubUser {
생성자는 정의하는 습관을 들여주세요~

2022-06-25 02:00 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/AuthService.java
> +    public AuthService(
너무 일반적인 이름이죠. 요것도 사용하는 클라이언트가 확실히 인지하게 `Github` 을 넣어줍시다.
여러개가 나오면, 이제 추상화를 해야겠죠.
나중에 Google 이 나오면 추상화를 해야겠다. 라고 염두에 두고 추상화까지 해보면 많은 경험이 될겁니다.

2022-06-25 02:00 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +        User user = User.of(githubUser);
`User`는 `GitHubUser`가 있다는걸 모르는게 좋습니다.
그러면 `GitHubUser` 가 변경되면 `User`도 변경의 여파를 갖게되거든요.
'변경' 에 대해서 항상 고려하는 습관을 들여주세요.

2022-06-25 02:00 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +        findUser.update(user);
이렇게 되면 `save` 한다음에 또 변경을 하겠죠?
우리 `Hibernate`는 똑똑해서 한 번에 처리해주겠지만, 좀 더 알맞게 풀어내봅시다.

2022-06-25 02:00 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +    public String getJwtToken(GithubUser githubUser) {
`get` 인데 `Transactional` 이 `readOnly`가 아니네요. 사용하는 입장에서 생각할 거리가 많아질 것 같습니다.

2022-06-25 02:00 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +        User user = upsertUser(githubUser);
여기서 질문입니다. `upsertUser` 는 의도한대로 `@Transactional` 이 동작할까요?

2022-06-25 02:00 UTC, ksundong commented on gradle/wrapper/gradle-wrapper.properties
> -distributionBase=GRADLE_USER_HOME
이 파일도 왜 지워주셨죠?

2022-06-25 02:00 UTC, ksundong commented on gradlew
> -#!/bin/sh
요것도요.

2022-06-26 11:18 UTC, merged

2022-06-27 01:55 UTC, donggi-lee-bit commented on .gitignore
> -
프로젝트 초기에 프로젝트를 생성하면서 `/be` 와 같이 백엔드 패키지에 한 번 감싸서 만들었어야했는데 그걸 안 해서 뒤늦게 패키지를 생성하여 파일을 옮기다가 빠진 것 같습니다 ㅜㅜ 수정해놓도록 하겠습니다

2022-06-27 01:57 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/controller/LoginController.java
> +    public ResponseEntity<Void> login() {
github으로만 로그인 기능이 이루어질 것 같아서 `login`으로 수정했는데 그래도 명시해주는 편이 나을 것 같네요..!! 수정하겠습니다!

2022-06-27 02:08 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/controller/dto/AuthLoginDto.java
> +@RequiredArgsConstructor
아래 블로그에서 `lombok` 사용 시 주의점 글을 읽었을 때 `RequiredArgsConstructor` 사용의 위험성을 알 수 있었습니다. 기존에 작성된 필드의 순서를 바꾸면 `RequiredArgsConstructor` 애노테이션을 통해 만들어지는 생성자의 파라미터 순서가 필드 선언 순서에 따라 바뀌게 됩니다. 그래서 `RequiredArgsConstructor` 애노테이션을 사용할 때는 이 점을 인지하고 사용하여야겠다고 생각했습니다!

https://kwonnam.pe.kr/wiki/java/lombok/pitfall

2022-06-27 02:09 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/dto/GithubUser.java
> +public class GithubUser {
생성자 정의!! 하도록 하겠습니다, 감사합니다!!

2022-06-27 03:31 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/AuthService.java
> +    public AuthService(
확실히 `Github` 을 붙여주는 게 좋을 것 같습니다! 또 Google과 같이 여러 OAuth 로그인이 있다면 `AuthService` 라는 인터페이스나 추상 클래스를 두고 구현체로 `GithubAuthSerice` `GoogleAuthService` 를 만드는 방법이 좋을 것 같네요!! 감사합니다!

2022-06-27 05:14 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +        User user = User.of(githubUser);
오 그런 점까지 생각하지 못했습니다..!! 변경에 대해서 고려하여 코드 작성할 수 있도록 하겠습니다. 
로직은 `GithubUser` 내부에서 `User` 를 만들어줄 수 있도록 변경해보도록 하겠습니다!!

2022-06-27 05:15 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +        findUser.update(user);
맞습니다 😅 좀 더 고민해서 변경사항이 있을 때만 `update` 될 수 있도록 변경해보겠습니다!

2022-06-27 05:20 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +    public String getJwtToken(GithubUser githubUser) {
오우 `readOnly` 옵션 붙여주도록 하겠습니다!

2022-06-27 07:33 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +        findUser.update(user);
`authId` 로 해당 `user` 가 DB 에 저장되어 있는지 유무를 확인하고, 이미 존재하는 회원이면 `update` 메서드를 실행 시켜 업데이트한 뒤 `findUser` 변수에 담고, 존재하지 않는 회원이라면 그대로 `user` 를 `findUser` 변수에 담아 `JpaRepository` 의 `save` 메서드를 실행할 수 있도록 수정하고자 합니다!

```java
User findUser = userRepository.findByAuthId(user.getAuthId())
            .map(u -> u.update(user))
            .orElse(user);
        return userRepository.save(findUser);
```

2022-06-27 07:45 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +        User user = upsertUser(githubUser);
`@Transactional` 이 제대로 동작할 지에 대해 생각을 해보았습니다.
지금의 로직에서는 `pk` 로 `user` 를 조회하고 있지 않다보니 엔티티가 영속성 컨텍스트에 등록되지 않고 그로인해 JPA의 더티체킹이 이루어지지 않습니다.
그래서 `update` 메서드가 실행된 이후에 `save` 를 따로 해주지 않아 `update` 한 유저 정보가 반영되지 않습니다.

2022-06-27 13:08 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/controller/dto/AuthLoginDto.java
> +@RequiredArgsConstructor
네 디자인 원칙 중에 이런 것도 있어요.

```
같은 타입을 중복해서 사용하지 말라
```

왜인지도 생각해보세요~

2022-06-27 13:14 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +        findUser.update(user);
`map`에서 뭔가 변경하는 동작은 사실 되게 어색하긴한데요.
Java니까 그냥 넘어갑시다.
그리고 여기선 `u` 보다는 `foundUser` 정도로 명명해주면 좋겠네요.

2022-06-27 13:15 UTC, ksundong commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +        User user = upsertUser(githubUser);
@donggi-lee-bit 
Spring 의 Transactional 의 동작 원리에 대해서 학습해보시길 바랍니다.

2022-06-27 17:02 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/service/LoginService.java
> +        User user = upsertUser(githubUser);
`Transactional` 동작 원리에 대해 학습하여 다음 PR에 학습한 내용도 같이 작성하겠습니다!

2022-06-27 17:37 UTC, donggi-lee-bit commented on be/src/main/java/be/codesquad/issuetracker/oauth/controller/dto/AuthLoginDto.java
> +@RequiredArgsConstructor
같은 타입을 중복해서 사용했을 때 `@RequiredArgsConstructor` 애노테이션으로 생성자를 만들어 사용하게 되면

```java
private final int cancelPrice;
private final int orderPrice;

// 필드의 선언 순서가 아래와 같이 바뀌었을 때
private final int orderPrice;
private final int cancelPrice;

new SomeClass(5000, 10000);
```

구현체를 만드는 쪽에서 파라미터 값을, 바뀐 필드의 순서에 맞게끔 수정하지 않아도 다른 문제 없이 실행됩니다.
하지만 기대한 값과는 다른 결과이기 때문에 이러한 문제가 발생할 수 있다고 생각합니다!