[team-23(BE)] IssueTracker - 이슈 저장, 필터링 로직 수정
codesquad-members-2022/issue-tracker pull request #218
Opened 2022-06-28 08:34 UTC by ak2j38

## 3주차 1번째 PR
- dan😁 안녕하세요! 로니와 아더입니다. 
- 3주차 첫 번째 PR을 보냅니다! 
- 남은 기간도 잘 부탁드립니다! 

## 진행 사항

### 1. 이슈 저장 및 조회 로직 구현 및 수정
  - 이슈 저장 로직 및 디테일 조회 로직, 필터링 로직을 구현했습니다.
  - 필터링을 위해 객체를 전달받는 대신 `id`를 전달받도록 수정했습니다.
  - 위의 변경사항에 따라 `queryDSL` 수정했습니다.

2022-06-28 14:08 UTC, Hyune-c requested changes
수고하셨습니다.

2022-06-28 14:08 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/AuthorizationExtractor.java
> +import org.springframework.stereotype.Component;
불필요한 import를 정리하는 것도 클린 코드의 하나라고 생각해주세요.

2022-06-28 14:08 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/AuthController.java
> +        MemberDto findMember = memberService.findMember(userId);
`nit` 
이 과정을 `LoginArgumentResolver`에서 하는 방법도 있을 것 같습니다.

2022-06-28 14:08 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/LabelController.java
> +    @ResponseStatus(HttpStatus.OK)
`200 OK`는 기본 값이기에 명시해주지 않아도 됩니다.

2022-06-28 14:08 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueDetail.java
> +@ToString
web 레이어의 dto라면 괜찮긴 하지만, 기본적으로 `ToString`의 활용을 권장하지 않습니다.

2022-06-28 14:08 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/milestonedto/MilestoneResponse.java
> +@AllArgsConstructor
`nit` 정적 팩토리 메서드를 위한 생성자라면 접근 제한자를 설정하는 것을 권장합니다.

2022-06-28 14:08 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/domain/issue/Issue.java
> +    @OneToMany(mappedBy = "issue", cascade = CascadeType.PERSIST, orphanRemoval = true)
cascade를 보수적으로 사용하는 것은 좋은 습관입니다. 👍

2022-06-28 14:08 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueRepository.java
> +    Optional<Issue> findById(@Param("id") Long id);
`nit` 단순히 n+1을 막기 위함이라면 `@EntityGraph`를 활용하는 방법도 있습니다.
개인적으로는 jpql보다는 querydsl을 선호하긴 합니다.

2022-06-28 14:08 UTC, Hyune-c commented on BE/src/test/java/com/ron2ader/issuetracker/service/IssueServiceTest.java
> +        assertThat(createdIssueId).isEqualTo(4L);
SQL을 통해 생성된 issue가 3건 존재하기에 4라고 표현하셨군요..
SQL이 수정되면 영향을 받을 테스트인 것 같습니다.

2022-06-28 14:08 UTC, Hyune-c commented on BE/src/test/java/com/ron2ader/issuetracker/domain/issue/IssueAssigneeRepositoryTest.java
> +    }
단언문이 없는 테스트는 매우 이상합니다.

2022-06-28 14:08 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/service/MilestoneService.java
>      }
`nit` 
web 레이어의 response dto가 service 레이어에서 생성되고 있군요.
지금 규모에서는 나쁘지 않은 설계이지만 `레이어 역류`에 대해 알고 가시면 좋을 것 같습니다.

https://hyune.gitbook.io/hyune-wiki/and/codesquad/22reviewer/undefined/service-dto

2022-06-29 05:41 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/auth/AuthorizationExtractor.java
> +import org.springframework.stereotype.Component;
넵! 커밋전에 확인하는 습관 들이도록 하겠습니다!

2022-06-29 07:43 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/controller/LabelController.java
> +    @ResponseStatus(HttpStatus.OK)
`200 OK`가 기본값인지 몰랐습니다. 😅
앞으로는 생략하겠습니다!

2022-06-29 07:43 UTC, CMSSKKK commented on BE/src/test/java/com/ron2ader/issuetracker/domain/issue/IssueAssigneeRepositoryTest.java
> +    }
잠시 쿼리 및 값을 확인해보려고 했었는데, 수정하지 못했던 것 같습니다. 수정하겠습니다!

2022-06-29 07:44 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueDetail.java
> +@ToString
넵!  단순히 넘어오는 값 확인을 위해 추가했던 `ToString`인데 필요없는 코드들은 삭제하도록 하겠습니다.

2022-06-29 07:47 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/controller/milestonedto/MilestoneResponse.java
> +@AllArgsConstructor
정적 팩토리 메소드를 위한 롬복 생성자라면 접근 제한자(`PROTECTED`, `PRIVATE`)를 꼭 추가하겠습니다.

2022-06-29 08:02 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/service/MilestoneService.java
>      }
작성해주신 글 덕분에 dto와 레이어에 대해서 조금 더 이해하게 된 것 같습니다! 

설게를 진행할 때, 재사용성과 dto를 범용적으로 활용할 수 있는지에 대해서 더 고민해보도록 하겠습니다

2022-06-29 08:10 UTC, CMSSKKK commented on BE/src/test/java/com/ron2ader/issuetracker/service/IssueServiceTest.java
> +        assertThat(createdIssueId).isEqualTo(4L);
말씀대로 당장 통과만을 위한 테스트인 것 같습니다.
당장 이 테스트에서는 반환된 아이디로 다시 이슈를 찾아와서 값을 검증하는 것이 맞을까요??

그리고 data.sql의 역할은 applicaition이 실행할 때 기본적으로 들어가야할 데이터들을 저장하는 용도라고 다른 클래스원에게 들은 적이 있습니다.

test에서 data.sql을 사용하는 것에 대해서 어떻게 생각하시나요??

2022-06-29 08:22 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueRepository.java
> +    Optional<Issue> findById(@Param("id") Long id);
N+1 문제를 해결하는 방법들에 대해서 학습해보았습니다.

1. `join fetch` 사용
2. `@EntityGraph` 사용

두 방법의 공통점은 필요한 컬렉션들을 `Eager`로 가져와 불필요한 N+1 쿼리를 방지한다는 것이고 차이점으로는 `join fetch`는 inner join을 사용하고 `@EntityGraph`의 경우에는 left outer join을 사용해 불필요한 row가 많이 생길 수 있다는 점입니다.

2022-06-29 08:27 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/controller/AuthController.java
> +        MemberDto findMember = memberService.findMember(userId);
어떤 API에서는 `Member`를 db에서 조회할 필요가 없을 것이라고 생각해서 이렇게 설계했었는데, `argumentResolver` 활용에 대해서 더 공부해보겠습니다.

2022-06-29 08:42 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueRepository.java
> +    Optional<Issue> findById(@Param("id") Long id);
네. 그렇습니다. 심화 설명을 하자면

- `EntityGraph`를 사용하면 left outer join을 통해 불필요한 row가 생길 수 있는 것은 맞지만 
    - 먼저의 코멘트처럼 별도의 로직이 없이 단순히 n+1을 막기 위함이라면 고려할 수 있습니다.
    - 만약 그것으로 인해 성능이 문제가 간다고 하면 이미 이상한 설계이거나 다른 방법을 고려해야합니다.
    - `OneToFew` 개념에 대해 공부하시면 좋습니다.
- JPQL은 typesafe하지 않기에 개인적으로는 선호하지 않습니다.

2022-06-29 08:44 UTC, Hyune-c commented on BE/src/test/java/com/ron2ader/issuetracker/service/IssueServiceTest.java
> +        assertThat(createdIssueId).isEqualTo(4L);
저라면 given 절에서 기존 issue개수를 체크하고, 예상되는 값을 그 값의 +1로 할 것 같아요.
이러면 SQL이 변경되어도 괜찮겠죠.

---

test에서 data.sql을 사용하는 것은 괜찮은 방법입니다.
Import 어노테이션을 활용할 수도 있구요.

하지만 운영용 sql과 tesst용 sql은 분리하는 것을 권장합니다.

2022-06-29 08:45 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/controller/milestonedto/MilestoneResponse.java
> +@AllArgsConstructor
~~사실 저도 실무에서는 누락하곤 합니다.~~

2022-06-29 15:42 UTC, CMSSKKK commented
안녕하세요 단! 

아직 많이 부족한데... 내일 벌써 수료식이네요😅

불필요한 Import문이 너무 많아서 수정파일이 엄청 많이 생겼습니다.. 습관 잘 들이도록 하겠습니다. (수정사항을 보시기 불편할 것 같아서 걱정입니다.)

또한 `argumentResolver`만으로 로그인 검증이 필요한 api를 모두 커버하려면, member의 정보가 필요없는 api에도 파라미터로 `@Login`어노테이션을 부착해줘야하는 문제가 있어서 `interceptor`를 다시 추가하게되었습니다. 

마지막 PR이 남았지만, 감사인사 먼저 드립니다. 
3주간 친절하고 세심한 리뷰덕분에 많이 배웠습니다.

2022-06-29 19:32 UTC, Hyune-c approved these changes

2022-06-30 02:22 UTC, merged