[Team-30] [BE] 3주차 두 번째 PR
codesquad-members-2022/issue-tracker pull request #220
Opened 2022-06-28 17:37 UTC by nathan29849

안녕하세요 Dan! 나Dan입니다!

오늘부터 하루 한 개씩 PR을 날리는 것을 목표로 기능구현에 매진하려 합니다.(많이 늦어진 점 죄송합니다.)

이번 PR 주된 내용:
- Milestone 수정 기능
- Milestone 삭제 기능
- Milestone progressRate 계산

2022-06-28 17:37 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/application/MilestoneService.java
>  			.collect(Collectors.toList());
dueDate가 null이 아닐 때만 계산하기 위해 filter를 두 번 사용하였습니다.

2022-06-28 17:39 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/infrastructure/MilestoneRepository.java
> +	List<Milestone> findAll();
fetch join을 하기 위해 `@EntityGraph` 어노테이션을 사용하였습니다.

2022-06-28 17:39 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/infrastructure/MilestoneRepository.java
> +	List<Milestone> findAll();
이를 통해 N+1 문제를 해결할 수 있었습니다.

2022-06-28 17:40 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/controller/MilestoneController.java
> +		MilestoneIdDto milestoneId = milestoneService.add(milestoneCreateRequest);
`IssueIdDto` 와 같이 Id에 대해 Dto로 처리해주었기 때문에 일관성을 위해 `MilestoneIdDto`로 처리해주었습니다.

2022-06-29 01:44 UTC, Hyune-c requested changes
수고하셨습니다.

2022-06-29 01:44 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/application/MilestoneService.java
> +	}
전체적으로 레이어 구분이 모호한 부분이 존재하네요.
이 메서드를 기반으로 몇 가지를 말하겠으니, 문제가 될만한 점을 생각해보시면 됩니다.

참고로 이 내용은 절대적인 것이 아닙니다.
오히려 충분히 작은 프로젝트에서는 이것을 엄격히 지키지 않는 경우도 있습니다.
트레이드 오프의 대상이라고 생각해주시면 됩니다.

1. service 레이어에서의 반환 값이 web 레이어에서 그대로 반환되고 있다.
2. 어떤 반환값은 response라는 단어가 들어가 있고, 어떤 것은 그렇지 않아 일관성이 떨어진다.
3. web 레이어의 request가 service 레이어에서 그대로 사용되고 있다.

2022-06-29 01:44 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/infrastructure/MilestoneRepository.java
> +	List<Milestone> findAll();
EntityGraph는 n+1을 해결할 수 있는 훌륭한 방법입니다.
하지만 고려할 것은 있습니다.

- LazyLoding의 대상이 충분히 OneToFew인가를 고려해야만 합니다.
- LazyLoding이 필요한 니즈가 있다면 사용을 달리해야 합니다.

개인적으로 저는 LazyLoding을 무시해야되는 상황이라면 querydsl을 사용하는 편입니다.

2022-06-29 01:44 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneDto.java
>  	private final LocalDate dueDate;
LocalDate, LocalDateTime 자체가 이미 timezone이 빠진 타입인데, timezone을 넣는게 의미가 있나요?
혹시 KST로 바꾸면 자동으로 +9가 되는건가요?

이건 저도 생각해본 적이 없던 것이라 테스트를 해보셨는지 궁금합니다.

2022-06-29 04:17 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/infrastructure/MilestoneRepository.java
> +	List<Milestone> findAll();
일반적인 Join Fetch와는 달리 @EntityGraph는 outer join으로 가져오므로 OneToFew인지 고려하라는 말씀이시군요! 감사합니다!

2022-06-29 04:25 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneDto.java
>  	private final LocalDate dueDate;
말씀해주신대로 timezone을 넣는 것이 아무런 의미가 없었습니다.
KST로 바꾸더라도 +9가 되지 않았습니다.
없애도록 하겠습니다!

2022-06-29 04:56 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/application/MilestoneService.java
> +	}
1, 3 그럼 이를 해결하기 위해서는 Web 레이어에서 사용하는 DTO와  Service 레이어에서 사용하는 DTO로 나누어 하는 것인가요?
2. 일관성을 신경써서 네이밍을 하지 못했던 것 같습니다. 앞으로 신경쓸 수 있도록 하겠습니다.

2022-06-29 05:05 UTC, Hyune-c commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/application/MilestoneService.java
> +	}
https://hyune.gitbook.io/hyune-wiki/and/codesquad/22reviewer/undefined/service-dto

네. 위를 생각해봐주세요. 
트레이드 오프의 대상임으로 적용 여부는 직접 판단하시면 될 것 같습니다.

2022-06-29 05:08 UTC, nathan29849 commented on BE/src/main/java/codesquad/backend/issuetracker/milestone/application/MilestoneService.java
> +	}
감사합니단!

2022-06-29 05:10 UTC, Hyune-c approved these changes

2022-06-29 05:11 UTC, merged