[Team-09][BE][테리&벅픽] 프로젝트 초기설정, 초기 API 설계, MockAPI 설정, 컨트롤러-도메인-DTO 초기 구성
codesquad-members-2022/issue-tracker pull request #39
Opened 2022-06-15 09:18 UTC by bugpigg

안녕하세요 `프레디`!
Team-09의 백엔드를 맡게 된 `테리, 벅픽` 입니다.
3주 기간 동안 잘 부탁드립니다! 🙇‍♂️ 🙇‍♀️

## 작업 내용

### ERD 그려보기, 초기 API 설계 및 Mock API 생성

<details>
<summary>ERD</summary>

![image](https://user-images.githubusercontent.com/91416897/173787026-f6a43623-2f99-4b17-a55b-77705c283714.png)
</details>

<details>
<summary>DB 다이어그램</summary>

![IssueTracker-team09 (5)](https://user-images.githubusercontent.com/91416897/173787344-46cf4cf4-a66e-4bfe-b5f4-67d1c90b5a8c.png)

- SQL문은 README 에 정리했습니다.
  https://github.com/bugpigg/issue-tracker/tree/BE/BE

</details>

<details>
<summary>초기 API 설계 및 Mock API 설정  </summary>

- Postman을 활용해 API Docs와 Mock를 생성하였습니다.
[API Docs](https://documenter.getpostman.com/view/20452796/UzBiNobv)
    
</details>

### 컨트롤러, 도메인, DTO 관련한 초기 설정

- 전체적인 프로젝트에 대하여 컨트롤러와 도메인 관련 클래스와 DTO 관련 클래스를 정의해보았습니다.

2022-06-15 17:40 UTC, Dae-Hwa reviewed
테리, 벅픽 안녕하세요!
며칠 안 됐는데 설계가 꽤 진행됐네요👍
덕분에 리뷰하다보니 커멘트도 많아졌네요 ㅋㅋ..

얘기를 나눴으면 하는 부분이 꽤 있어서 조금 진행되면 머지하겠습니다~

2022-06-16 01:50 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/comment/Comment.java
> +	private Issue issue;
issue와 comment는 1:n 관계로 저희가 설계했는데, 이 부분은 실수로 들어가게 되었습니다 ㅠㅠㅠ
수정하겠습니다!

2022-06-16 01:57 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/comment/CommentController.java
> +	@PatchMapping("/{id}")
`CommentController` 의  `update` 함수의 경우 자원의 일부분을 변경한다고 생각하여, Patch를 Http Method로 선택하였습니다!
다시 보니  `update` 함수 관련하여, Http Request Body에 대한 부분을 받는 파라미터를 설정해야 하는데 실수로 누락되었네요. 수정하겠습니다!

2022-06-16 01:59 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/comment/CommentController.java
> +	@PatchMapping("/{id}")
어떤 Http Method를 선택하더라도 서버의 로직대로 수행하게 되지만 
request로 받지 않은 기존 내용은 유지하고 변경된 내용만 수정한다는 컨벤션을 표현하기 위해 Patch를 선택했습니다 .

2022-06-16 02:00 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/comment/CommentController.java
> +		return ResponseEntity.ok(new CommentResponseDto());
엇 이 부분도 `201 Created` 로 초기에 설계했는데, 실수로 반영하지 못했네요! 수정하겠습니다!

2022-06-16 02:02 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/comment/CommentController.java
> +		return ResponseEntity.ok(new CommentResponseDto());
생성에 대해서는 201응답을 지정하기로 했었는데요. 해당 부분 작성을 반복적으로 하다 보니 실수가 있었습니다. 
처음에 Spring Rest Docs를 적용(현재는 적용 스킵상태)해보려고 컨트롤러의 API 전체 틀을 생성하였는데요. 
그렇게 하다보니 반복작업이 많아져서 실수가 많아지는 경향이 있었습니다.

2022-06-16 02:05 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/comment/Emogi.java
> +	private String unicodeValue;
> 이모지의 누적 개수
- 해당 부분에 대해 말씀해주셔서, 이모지와 코멘트가 N:M으로 중간테이블 필요성을 깨닫게 되었습니다. 

>  label을 설계하신 것 처럼 이모지 설계
- 이모지의 이름을 부여해(예 : smile ) 사용자가 이모지를 선택할 때 이모지 내용을 알게 하면 좋을 것 같습니다.

2022-06-16 02:07 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/comment/EmogiController.java
> +	@PostMapping("/emogi")
프레디 생각에 동의합니다. 이모지가 커멘트에 종속적인 리소스여서 같은 도메인으로 바라보고, 같은 패키지에 두었습니다. 
하지만 Controller까지 같이 사용할 생각을 하지 못했었습니다. 
Repository가 다르면 Controller도 다를 것이라 생각한 것 같습니다.

2022-06-16 02:09 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/comment/Emogi.java
> +	private String unicodeValue;
엇 말씀대로 `emogi` 같은 경우도 `label` 과 유사하게, `comment` 와 n:m 관계로 표현하는게 명확한것 같습니다!

2022-06-16 02:10 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/common/BaseTimeEntity.java
> +	private LocalDateTime createdDate;
네이밍에 조금 더 많은 것을 담을 수 있도록 신경쓰겠습니다.

2022-06-16 02:13 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/issue/Issue.java
> +public class Issue extends BaseTimeEntity {
일단은 단방향연관관계만 맺고 엔티티를 빠르게 작성해보았습니다. 
오늘부터 본격적으로 API를 개발하면서 Issue에서 assignee와 label을 가지고 있을 것인지,
또는 독립적인 도메인으로 볼 것인지 생각해보게 될 것 같습니다. 

잠깐 생각한바로는
label은 종속적으로 가지고 있어도 좋을 것 같습니다. 
이 부분에서 질문이 있는데요. 그렇게 되면 issue와 label이 양방향 관계를 가질 수 밖에 없게 되는 것인가요?

2022-06-16 02:14 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/comment/EmogiController.java
> +	@PostMapping("/emogi")
맞습니다!
그렇지만 초기 구성이여서 컨트롤러부터 분리하여 코드를 작성해보았습니다.
추후 리팩토링 과정에서, `comments/emogi` 와 같은 방식으로 URL을 표현해보는 것에 대해 생각해보겠습니다!

2022-06-16 02:15 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/common/BaseTimeEntity.java
> +	private LocalDateTime createdDate;
엇 넵 이 부분은 변수 네이밍에 있어서 꼼꼼하지 못했습니다!
수정하겠습니다!

2022-06-16 02:23 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/image/ImageController.java
> +	public void findPreSignedUrl() {
요구사항에, 사용자가 이슈작성란에 이미지를 업로드하면 이미지 주소를 삽입해준다는 사항이 있었습니다.

위 기능을 위해 다음과 같은 과정으로 API를 구현하려 합니다.
```
1. 클라이언트에서 이미지 업로드 요청
2. 서버는 AWS S3에 preSignedURL 요청
3. AWS에서 preSignedURL 반환
4. 서버는 클라이언트에게 preSignedURL 전달
5. 클라이언트에서 preSignedURL로 이미지 upload
```

그래서 위 코드는 AWS S3에서 preSignedURL 요청하고, 반환받은 URL을 클라이언트에게 전달해주기 위해 작성하였습니다.

2022-06-16 02:32 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
> +	@GetMapping(":type=filter")
엇 이 부분에도 실수가 있었습니다ㅠㅠ 
세미콜론으로 표기하려고 하였는데 실수로 콜론을 사용했네요

다음 링크를 참고하여 작성하게 되었는데요. 세미콜론의 경우 URL의 비계층적인 부분을 표현하기 위해 사용한다고 합니다.
참고링크: https://www.oreilly.com/library/view/restful-web-services/9780596809140/ch04.html

그래서 `@GetMapping(";type=filter")` 을 사용한 저희의 의도는
검색의 경우, 제목 기반의 검색과 필터 기반의 검색으로 종류가 나누어진다고 판단하여 이를 구분하기 위해 사용하게 되었습니다.

2022-06-16 02:35 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
> +		@ModelAttribute final String issueSearchDto) {
검색조건에 대해서는 정해졌는데, DTO 클래스 작성을 빼먹었습니다.
추후 커밋에 반영하겠습니다!

2022-06-16 02:36 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/label/Label.java
> +	private boolean idDarkMode;
엇 넵 맞습니다.. 오타가 많네요 수정하겠습니다!

2022-06-16 02:39 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/member/Member.java
> +	private String imgUrl;
넵 이 부분은 유저의 프로필 사진 URL로, 단일 품목이라 따로 관리하지 않기로 하였습니다.

2022-06-16 02:41 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/member/Member.java
> +public class Member {
`Member` 부분은 추후 OAuth와 JWT 학습을 병행하며 진행할 계획입니다. 그래서 아직 설계를 완성하지 못했습니다.

2022-06-16 02:42 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/milestone/Milestone.java
> +	private LocalDate completion_date;
엇 이 부분도 주의 깊지 못했네요. 수정하겠습니다!

2022-06-16 02:57 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
> +	public ResponseEntity<CommonResponseDto> updateAllState(@RequestParam final Boolean setClose,
그럼 `setClose`를 `close`로 쿼리파라미터의 키로 사용하면 될까요?

` close를 상태`로 생각해본다는 문장을 저와 벅픽 모두 이해하지 못했어요~

2022-06-16 03:11 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/member/Member.java
> +public class Member {
Member의 `userId` 값은 중복이 가능하도록 기획하였습니다. 
이유는, 여러 서드 파티의 userId값으로 사용하는 부분이 같을 수 있기 때문입니다. 
만약 apple의 userId는 이메일인데, 일반 회원도 userId를 이메일을 사용할 경우 같을 수 있기 때문입니다.

2022-06-16 03:14 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/member/MemberType.java
> +	GITHUB, APPLE, GENERAL;
아직 인증을 개발하지는 않았지만 여러 개의 로그인 방법을 선택할 수 있습니다. 
여러 개 로그인 방법을 제공하면 해당 MemberType Enum에 더 추가해야 할 사항이 있을까요?

2022-06-16 03:17 UTC, bugpigg commented on BE/src/main/resources/application.yml
> +        dialect: org.hibernate.dialect.MySQL8Dialect
현재 학습하고 있는 책이 8버전을 기반으로 설명하고 있는 책이여서 위와 같이 설정하게 되었습니다.

2022-06-16 05:15 UTC, Dae-Hwa commented on BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
> +	@GetMapping(":type=filter")
매핑해주는 기능이 따로 있는 줄 알았네요 ㅋㅋ
현재 구현해서 해당 핸들러와 연결되고 있는게 맞나요?

2022-06-16 05:45 UTC, Dae-Hwa requested changes

2022-06-16 05:45 UTC, Dae-Hwa commented on BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
> +	@GetMapping(";type=filter")
매핑해주는 기능이 따로 있는줄 알았네요 ㅋㅋ
추가로 현재 구현만으로 매핑해둔 핸들러 접근이 가능한지,
type에 title과 filter는 동시에 올 수 없다고 생각하신건지 궁금합니다!

2022-06-16 05:45 UTC, Dae-Hwa commented on BE/src/main/java/com/team09/issue_tracker/image/ImageController.java
> +	public void findPreSignedUrl() {
과정은 이해됐습니다! get 메소드에 void로 돼있어서 어떤 방법인건지 궁금했어요 ㅎㅎ

2022-06-16 05:45 UTC, Dae-Hwa commented on BE/src/main/java/com/team09/issue_tracker/issue/Issue.java
> +public class Issue extends BaseTimeEntity {
네 Label을 미리 등록하는 구조가 맞다면 Issue와 Label은 N:M관계일건데요
이 부분은 관계테이블을 생성하면서 처리된 것 같고 객체끼리의 관계설정을 어떻게 할지 고민해보시면 될 것 같습니다!

2022-06-16 05:45 UTC, Dae-Hwa commented on BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
> +	public ResponseEntity<CommonResponseDto> updateAllState(@RequestParam final Boolean setClose,
Issue의 상태가 `CLOSE` 인지 `OPEN` 인지로 나타낼 수도 있을 것 같다는 뜻이었습니다. 지금은 상태가 두개라 boolean만으로 표현되니 이건 참고만 해주시고요
boolean 네이밍은 가능성을 나타내는 표현이 적절할 것 같아요
isClose shouldClose 이런 식으로요

2022-06-16 05:45 UTC, Dae-Hwa commented on BE/src/main/java/com/team09/issue_tracker/member/Member.java
> +	private String imgUrl;
어떤 이미지인지 같은 메타데이터를 넣어야 한다면 필요할 수도 있겠지만,
꼭 관리할 필요는 없고 어떤 식으로 얘기하시고 설계한지 궁금해서 여쭤봤습니다 ㅎㅎ

2022-06-16 05:45 UTC, Dae-Hwa commented on BE/src/main/java/com/team09/issue_tracker/member/MemberType.java
> +	GITHUB, APPLE, GENERAL;
Memeber에서는 type을 하나만 갖는데 모두 가능한 케이스는 GENERAL로 잡으시는건가요?

2022-06-16 05:45 UTC, Dae-Hwa commented on BE/src/main/java/com/team09/issue_tracker/member/Member.java
> +public class Member {
그럼 같은 이메일을 가진 여러명의 유저가 있을 수도 있겠군요
구현을 잘 하면 되기야 하겠지만, member의 id만 가지고 고유한 유저인지 판단하면 같은 email로 중복 가입도 할 수 있는거 아닌가하는 생각이 드는데요
비밀번호가 없는 것 같긴 한데, 제가 이해한게 맞다면 일반회원이 email로 로그인을 하는 경우는 해당 email을 가진 모든 계정을 탐색해서 확인해야 하는걸까요?

2022-06-16 05:47 UTC, Dae-Hwa requested changes

2022-06-16 05:47 UTC, Dae-Hwa commented on BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
> +	public ResponseEntity<CommonResponseDto> updateState(@PathVariable final Long id, @RequestParam final Boolean setClose) {
setClose 수정 부탁드려요~

2022-06-16 06:34 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/image/ImageController.java
> +	public void findPreSignedUrl() {
아 넵! 반환값도 URL 관련 DTO를 설정했어야 했는데 놓쳤습니다. 
추후 커밋에 포함되도록 하겠습니다!

2022-06-16 06:39 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
> +	public ResponseEntity<CommonResponseDto> updateAllState(@RequestParam final Boolean setClose,
아~ 이해했습니다!
Issue의 상태를 단순 boolean 으로 표현하는 것보다는, `CLOSE`나 `OPEN` 으로 ENUM을 활용해 표현하는 것이 추후에 다른 상태가 추가되었을때 변경이 적을것 같습니다!

쿼리 파라미터의 키는 말씀대로 수정해보겠습니다!

2022-06-16 07:17 UTC, Dae-Hwa commented on BE/src/main/resources/application.yml
> +        dialect: org.hibernate.dialect.MySQL8Dialect
학습하실때 다른 버전과 어떤 차이와 장단점이 있는지도 함께 보시면 좋을 것 같네요 ㅎㅎ

2022-06-16 08:43 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/member/MemberType.java
> +	GITHUB, APPLE, GENERAL;
같은 사람이라도 다른 로그인 방법을 선택하면 다른 유저로 간주하도록 하였습니다. 
GENERAL은 일반 회원을 뜻하는 것으로 기획했습니다.

2022-06-16 08:47 UTC, mybloom commented on BE/src/main/java/com/team09/issue_tracker/member/Member.java
> +public class Member {
>  member의 id만 가지고 고유한 유저인지 판단하면 같은 email로 중복 가입
- 네 다른 TYPE일 경우 이메일이 중복될 수 있습니다. 

> 비밀번호가 없는 것 같긴 한데, 제가 이해한게 맞다면 일반회원이 email로 로그인을 하는 경우는 해당 email을 가진 모든 계정을 탐색해서 확인해야 하는걸까요?
- 비밀번호는 추가 되어야 하는 부분인데 잊었던 것 같습니다. 추가해서 반영하도록 할께요~
- 일반 회원이 email로 로그인하는 경우는 , type와 userId를 조건으로 함께 탐색해서 확인하게 됩니다.

2022-06-16 11:35 UTC, Dae-Hwa commented on BE/src/main/java/com/team09/issue_tracker/member/Member.java
> +public class Member {
아직 구현을 하지 않아서 상상이 잘 가지 않을 수도 있을 것 같아요 ㅎㅎ 계속 고민해보시면 좋은 구조가 나올 것 같네요👍

2022-06-16 14:18 UTC, bugpigg commented on BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
> +	@GetMapping(";type=filter")
넵, 현재 코드에서 핸들러 접근이 가능합니다!

실제 서비스에서는 `title`과 `filter`를 동시에 검색조건으로 활용할 수 있어야 한다고 생각합니다
그렇지만 초기에는 분리해서 구현 및 테스트를 진행해보고, 추후에 수정하는 방향으로 생각했습니다!

2022-06-16 14:57 UTC, Dae-Hwa approved these changes

2022-06-16 15:00 UTC, Dae-Hwa approved these changes
변경 확인 했습니다 pr이 좀 길어졌네요
고생 많으셨습니다~

2022-06-16 15:00 UTC, Dae-Hwa commented on BE/src/main/resources/logback-spring.xml
> +  <springProfile name="console-log">
나중에 여유가 된다면 appender를 활용하는 방법도 시도해보시면 좋을 것 같아요 ㅎㅎ
이번 프로젝트에서는 굳이 안 바꾸셔도 상관 없습니다!

2022-06-17 01:33 UTC, merged