[team-25] [BE] 1번째 PR
codesquad-members-2022/issue-tracker pull request #50
Opened 2022-06-15 12:19 UTC by fpzk5656

안녕하세요?브라이언!
첫번째 PR 요청 보냅니다.

스프링 시큐리티 없이 OAuth 로그인 하는 것을 구현해봤는데,
이론 학습은 나름 했지만 코드로 구현하려하니 뭘 어디서부터 손대고 만들어야할 지 전혀 감이 안오더라구요.
그래서 구글링해서 나온 어떤 분이 만든 예제를 거의 따라치듯 배끼면서 이해하려 노력했는데
작업 도중에 궁금한게 application설정파일 쪽에 oauth 클라이언트 정보와 비밀키를 입력했는데
github에 올릴 때 이게 입력된채로 올려져도 되는지 궁금합니다.

소중한 리뷰 감사합니다

2022-06-15 23:49 UTC, wheejuni requested changes
수고 많으셨습니다. 💯 
크리덴셜 보관하신 파일은 꼭 수정 부탁 드립니다.

2022-06-15 23:49 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/OauthAttributes.java
> +public enum OauthAttributes {
👍

2022-06-15 23:49 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/OauthRestController.java
> +		System.out.println(loginResponse.getEmail());
`logger` 사용합시다~

2022-06-15 23:49 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/OauthService.java
> +		// redisUtil.setData(String.valueOf(member.getId()), refreshToken);
redis를 직접 사용하지 말고 Spring 에서 추상화된 뭔가를 제공할걸요? 한번 찾아보시는 것도 도움 되겠네요.

2022-06-15 23:49 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/OauthService.java
> +	}
여기에서 값을 담을 클래스를 하나 설계해 보시는 것도 좋겠습니다~

2022-06-15 23:49 UTC, wheejuni commented on BE/src/main/resources/application-oauth.yml
> +      client-secret: ${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}
당연히 이렇게 보관하시면 안됩니다~ ㅎㅎ
배포 시점에 환경 변수나 기타등등 방법으로 딱 넘어갈 방법을 고민해 주시고 이 파일은 빨리 수정하시는게 좋지 않을까 싶습니다.

2022-06-15 23:49 UTC, wheejuni commented on BE/src/test/java/team25/issuetracker/IssueTrackerApplicationTests.java
> +@SpringBootTest
테스트가 너무 없네요. 아쉽습니다.

2022-06-16 05:41 UTC, fpzk5656 commented on BE/src/main/java/team25/issuetracker/OauthService.java
> +		// redisUtil.setData(String.valueOf(member.getId()), refreshToken);
jedis나 spring-boot-starter-data-redis를 말씀하시는걸까요?
금욜 PR까지 적용해보도록 하겠습니다😢

2022-06-16 05:55 UTC, fpzk5656 commented on BE/src/main/resources/application-oauth.yml
> +      client-secret: ${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}
아아 역시!
알겠습니다!
근데 궁금한게 있습니다.
상용화된 앱이나 웹페이지들은 연동 로그인할 때 
유저가 oauth 클라이언트id, 클라이언트 비밀키를 입력하지 않아도
예를 들어 구글 계정이랑 비번만 있어도 다른 앱이나 웹에 연동 로그인 할 수 있던데

유저의 이메일 로그인 상태만 있어도 클라이언트id,클라이언트 비밀키 없이도
토큰을 받을 수 있는 방법이 있을까요?

2022-06-16 07:26 UTC, fpzk5656 commented on BE/src/main/java/team25/issuetracker/OauthService.java
> +	}
엇...객체로 만들어서 보내주니까 동작에 계속 실패하고 있어서
확인해보니
 
![image](https://user-images.githubusercontent.com/59153422/174015495-261ee646-3995-438e-a721-d684dc42027e.png)


![image](https://user-images.githubusercontent.com/59153422/174015533-8dd6ef7b-5217-4c82-bf55-8f1470c5e243.png)
[https://binux.tistory.com/56](url)
webClient 사용시 body 부분에는 multiValueMap 을 사용하라는 의견이 많은데요.

클래스로 사용해야 하는 이유와 참고할만한 레퍼런스가 있을까요?ㅠㅠ

2022-06-16 23:19 UTC, wheejuni commented on BE/src/main/java/team25/issuetracker/OauthService.java
> +	}
아 제가 잘못 봤습니다;;
특정 상황에서만 사용하는 로직이면 지금 그대로 두셔도 됩니다.

2022-06-16 23:20 UTC, wheejuni commented on BE/src/main/resources/application-oauth.yml
> +      client-secret: ${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}
프론트, 모바일 개발자들과 고민해보세요~
서버의 영역은 아닌 듯합니다.

2022-06-22 02:50 UTC, merged