[team-23(BE)] IssueTracker - OAuth, 환경설정파일 분리, CORS 매핑
codesquad-members-2022/issue-tracker pull request #83
Opened 2022-06-17 06:07 UTC by ak2j38

## 1주차 2번째 PR
- dan😁 안녕하세요!  아더와 로니입니다. 
- 1주차 두 번째 PR을 보냅니다! 
- 3주동안 잘 부탁드립니다! 

## 진행 사항

### 1.  `Github OAuth` 기능 구현
  - `Github OAuth` 인증을 구현했습니다.
  - `id`와 `avatarUrl`을 가져와 기존 회원이라면 `update`, 신규 회원이라면 `save`하는 방식으로 진행했습니다.
  - 추후 회원가입 로직을 만든다면 업그레이드 예정입니다. 

### 2.  개발 / 운영 환경설정 파일 분리
  - `application.yml` 파일을 로컬 환경인 `-local`과 운영 환경인 `-prod`로 분리했습니다.
  - 필요시 `-test`환경설정 파일을 추가할 예정입니다. 

### 3. CORS 이슈 해결
  - `WebConfig.java` 클래스 파일 내에 CORS 매핑을 구현했습니다.

## 질문 사항
  - 코드상에 코멘트 남겨두려했으나 이번에 수정한 파일이 아니라 여기에 질문드립니다 😅
  - `IssueRepository.java`
 ```
    @Query(value = "SELECT i FROM Issue i JOIN FETCH i.issuer m WHERE i.openStatus = :openStatus",
            countQuery = "SELECT count(i.id) FROM Issue i WHERE i.openStatus = :openStatus")
    Page<Issue> findAllByOpenStatus(Pageable pageable, @Param("openStatus") Boolean openStatus);
```
  - 위 코드는 이슈의 상태에 따라 목록을 가져오는 쿼리 및 로직입니다. 
  - 이슈목록을 보여주기 위해 각 상태별 이슈의 갯수가 필요한데 이 과정에서 개선점이 있을까 고민입니다.
  - 아래는 고민했던 방법들입니다.
    1. 
    2. 전체 갯수에서 현재 상태의 갯수를 빼서 모든 상태의 갯수를 계산하는 로직으로 처리
  - 어떤 방법이 가장 추천되는 방식인지 궁금합니다.

2022-06-17 07:44 UTC, Hyune-c requested changes
수고하셨습니다.

---

> 현재 떠오로는 방식으로는 open, close 상태를 group by로 갯수를 세는 쿼리를 한번 더 보내서 조합하는 방식으로 생각 중입니다.

동적 조회/동적 쿼리를 고민해보시면 좋을 것 같습니다.

> 상태를 고려하지 않고 issue를 가져와서 자바에서 필터링하는 방법도 있을것 같습니다. (이 방법은 요구되는 사이즈를 맞추기 어려워서 좋은 방법이 아닌것 같습니다.)

애플리케이션에서 처리하는 방법으로 관계가 충분히 작다고 보장된다면 괜찮은 방법입니다.

> 한번의 쿼리로 해결가능하거나, 어떤 편이 더 좋을까요??

이건 스스로 업무 판단을 하셔야되는 영역입니다.

만약 저라면
- 전체 개수만 필요하다면 (전체 리스트 내용 X) 별도의 카운트 API를 만들 것 같습니다.

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/github/GithubToken.java
> +    private String tokenType;
`nit` 
`JsonProperty`는 보통 web 레이어에서 사용됩니다. 
때문에 혼동이 올 수도 있어서 저는 아예 사용을 지양하는 편입니다.

아마 github에서 반환되는 형태 때문에 `JsonProperty`를 사용하신 것 같은데,
외부 통신을 위한 dto는 그냥 원형 그대로의 스네이크 케이스를 사용하는 것도 괜찮지 않을까요?

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/AuthToken.java
> +    }
```java
validToken("Bearer aaa")
```

지금의 로직대로면 위 예시코드의 실행은 예외가 아닐 것 같습니다.

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/AuthToken.java
> +        return new AuthToken(split[0], split[1]);
지금의 코드를 보면 `AuthToken`을 생성하는데 필요한 제약 조건이 `from` 정적 팩토리 메서드에 들어있습니다.
그런데 `AllArgsConstructor`가 public 이네요..?

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/AuthToken.java
> +    private static final String BEARER = "Bearer";
이 업무를 모르는 개발자가 `BEARER`라는 변수명을 보면 무엇이라고 생각할까요?

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/JwtProvider.java
> +    private static final String JWT_ISSUER = "aderon2";
`nit`
이것들은 properties의 영역이라고 생각합니다.
그리고 token type은 enum으로도 할 수 있다고 생각합니다.

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/config/WebConfig.java
> +                .excludePathPatterns("/auth/github", "/auth/refresh");
`excludePathPatterns` 활용 좋네요. 👍

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/config/WebConfig.java
> +    }
`네이버 로그인` 연동 니즈가 생기면 이 코드가 어떻게 될까요?

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/JwtProvider.java
> +    }
`verify`의 반환형은 boolean이어야되지 않을까요?

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/domain/member/Member.java
> +        return this;
사용자의 update() 호출에 if문에 걸리지 않으면 `변경 없이 this가 반환`되네요.
어떻게 생각하시나요?

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/service/MemberService.java
> +    }
`nit` 
`save()` 호출에 대해 어떻게 생각하시나요.
hint. 더티 체킹, 영속성 컨텍스트

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/service/GithubOAuthService.java
> +            .block();
webClient는 webflux 라이브러리를 통한 기술 중 하나도 reactive 기술을 지원합니다.
그런데 block()은 동기 기술을 구현하는 것인데 어떻게 생각하시나요.

사실 이건 꽤 어려운 것이라 걍 넘어가셔도 무방합니다.

2022-06-17 07:44 UTC, Hyune-c commented on BE/src/main/resources/application-prod.yml
> +      ddl-auto: update
`nit`
ddl-auto를 upate로 쓰는건 처음 봤는데, 의도를 듣고 싶네요.

2022-06-18 08:18 UTC, ak2j38 commented on BE/src/main/resources/application-prod.yml
> +      ddl-auto: update
현재 개발중이라 엔티티가 자주 수정될 수 있어 `update`로 남겨두었습니다.

추후 운영환경은 `none`으로 처리해두고 실제 쿼리들로 운영할 예정입니다.

2022-06-18 08:19 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/service/GithubOAuthService.java
> +            .block();
이전에 여러번 외부 api를 사용할 때, `subscribe`를 활용한 적 있으나, 바로 `GithubToken` 을 받아서 사용해야한다고 생각해서 block을 사용했습니다. 

비동기 flow에 대해서 조금 더 공부하고 활용할 수 있도록 해보겠습니다!

2022-06-18 08:20 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/domain/member/Member.java
> +        return this;
`update()` 메서드를 호출했을때, 예상되는 결과와 다른 결과를 반환받을 수 있을 것 같아서 `isUpdatable()`메서드를 추가하였습니다!

2022-06-18 08:20 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/service/MemberService.java
> +    }
`memberRepository`에서 find로 가져왔으니 영속성 컨텍스트의 관리 범위에 있고 가져온 `member`를 단순히 변경만 해주면 JPA가 더티체킹을 통해 `update`를 해준다는 사실을 잠시 잊고 있었습니다.

해당 로직 `save()` 호출하지 않고 속성만 변경하도록 수정했습니다.

2022-06-18 08:23 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/JwtProvider.java
> +    }
메소드 반환형에 대해서 더 신경써서 코딩하겠습니다 😅

2022-06-18 08:23 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/config/WebConfig.java
> +    }
WebClient를 매번 새로 생성하지 않고 bean으로는 등록해야할 것 같은데, 이렇게 여러가지로 webClient로 외부와 통신을 해야할 때는 baseUrl을 두지 않고 사용해야하나요?? 

아니면 multi로 둘 수 있나요?? 이전에 검색을 해봤을 때.. multi로 하는 방법을 찾지 못해서 WebClient를 bean으로 여러개 두고 사용했었습니다. 

어떤 편이 좋을까요??

2022-06-18 08:24 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/JwtProvider.java
> +    private static final String JWT_ISSUER = "aderon2";
해당 필드들을 `auth.yml` 파일로 분리해 관리하도록 수정했습니다.

2022-06-18 08:25 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/AuthToken.java
> +    private static final String BEARER = "Bearer";
의미를 알아볼 수 없을 것 같습니다! 

`BEARER_TYPE` 으로 수정하긴 했는데... 더 명확하게 하면 `BEARER_TOKEN_TYPE`으로 해야할 것 같습니다!

2022-06-18 08:25 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/AuthToken.java
> +    }
순간 착각하고 메서드를 활용했던 것 같습니다. 수정했습니다!

2022-06-18 08:27 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/auth/github/GithubToken.java
> +    private String tokenType;
스네이크케이스와 카멜케이스에 대해서 통일성이 중요하다고 생각해서 활용하였습니다.

레이어의 역할에 대해서 고민하게 해주셔서 매번 감사합니다!

2022-06-18 08:28 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/AuthToken.java
> +        return new AuthToken(split[0], split[1]);
`@AllArgsConstructor`의 접근 제한 범위를 `private`으로 수정했습니다.

2022-06-18 08:30 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/auth/AuthInterceptor.java
> +        request.setAttribute("userId", audience);
request를 변경시키지 않는 방법 대해서 많이 찾아보고 고민하면서, 어노테이션과 ArgumentResolver를 활용해서 token을 검증하도록 로직을 수정했습니다!

2022-06-18 08:30 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/auth/AuthInterceptor.java
> +        }
`Optional`을 통해 개선을 했습니다. 
한 가지 궁금한 점이 있는데 만약 `tokenHeader`가 `null` 이라면 예외를 던져주는 것을 의도하신건가요??

2022-06-18 08:31 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/auth/AuthInterceptor.java
> +    private boolean isPreFlight(String httpMethod) {
코드를 작성한 이유에 꼼꼼하게 다시 살펴보면서, 주석을 남기거나 메서드네이밍을 더 고민하겠습니다!

2022-06-18 08:31 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/auth/AuthInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
단순히 기능 구현을 하고 있어 예외 핸들링을 크게 고려하지 않았습니다. 
구현하면서 예외 핸들링을 신경써서 코딩하겠습니다.

2022-06-18 08:34 UTC, CMSSKKK commented
현재 interceptor를 통해서 구현했던 로그인상태확인(토큰 검증) 로직을 `@Login` 어노테이션과 `ArgumentResolver`를 활용해서 코드를 수정했습니다.

수정하고 보니 interceptor의 활용이 당장 필요가 없을 것 같아서 interceptor를 삭제하였습니다

2022-06-18 09:25 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/AuthToken.java
> +    private static final String BEARER = "Bearer";
`BEARER`라는 단어는 추상부일까요? 구현부일까요?

https://velog.io/@cada/%ED%86%A0%EA%B7%BC-%EA%B8%B0%EB%B0%98-%EC%9D%B8%EC%A6%9D%EC%97%90%EC%84%9C-bearer%EB%8A%94-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C

2022-06-18 09:28 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/config/WebConfig.java
> +    }
네이버 접근용 webclient, 깃허브 접근용 webclient를 서로 다른 bean으로 생성시키고 주입할 수 있지 않을까요?

슈퍼 타입과 서브 타입까지 나아갈 수 있는 문제라서 조금 어려울 수도 있습니다.
지금은 넘어가셔도 좋습니다.

2022-06-18 09:28 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/domain/member/Member.java
> +        return this;
객체간의 협력에 대해 `묻지 말고 시켜라`를 좀 더 고민해보셨으면 좋겠습니다.

2022-06-18 09:47 UTC, Hyune-c requested changes

2022-06-18 09:47 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/AuthInterceptor.java
> +        }
```java
String token = request.getHeader(HttpHeaders.AUTHORIZATION);
```

아마 저라면 이 단계에서 `Optional.orElse()`를 활용했을 것 같아요.

---

네. 토큰이 null 이면 이후 로직을 타지 않게 하는 것이 좋은 접근이라고 생각합니다.

2022-06-18 09:47 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/service/MemberService.java
> +    }
어.. 이 메서드는 upsert를 의도하신 것 같은데, DB나 영속성 컨텍스트에 없는 member가 매개변수로 들어오면 throw 되어 버리네요.
그러면 upsert가 아니라 update 같은데, 이 메서드에서 insert가 될 수 있나요?

2022-06-18 09:47 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/AuthToken.java
> +    }
어.. 여전히 예외가 아니지 않나요? 
validate라면 `tokenType`만 비교하는 것이 아니라 token의 유효성을 판단해야 된다고 생각합니다.

- token의 유효기간이 정상인지
- token의 파싱이 잘 되는지

지금의 메서드는 `validateTokenType()`인 것 같아요.

2022-06-18 09:47 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/AuthInterceptor.java
> +        log.info("token={}", token);
`info`는 운영 환경에서도 확인하기 위한 로깅을 위해 사용됩니다.
token 정보는 운영 환경에서는 노출되면 안된다고 생각하기에 `debug`가 적절하다고 생각합니다.

2022-06-18 09:47 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/auth/AuthorizationExtractor.java
> +    }
오.. 이렇게 만들수도 있군요. 좀 신기하네요.
호불호가 갈리는 코드 스타일일 것 같습니다.

2022-06-18 10:28 UTC, ak2j38 commented on BE/src/main/java/com/ron2ader/issuetracker/service/MemberService.java
> +    }
다시 바뀐 로직을 살펴보니 `memberRepository`에서 member를 찾지못하면 예외를 던져버려서 insert가 불가능해지는 것을 확인했습니다.

`orElseThrow` 대신 `orElse`로 전달받은 `member`를 다시 돌려준 후 `save`하는 로직이 필요하다고 생각하는데 이때 `save()`를 사용하지 않고 처리할 수 있는 방법이 있을까요?

저희는 처음에 작성했던 로직에서 이상한 점을 발견하지 못해서 여쭤봅니다 ㅠ_ㅠ

2022-06-18 10:32 UTC, CMSSKKK commented on BE/src/main/java/com/ron2ader/issuetracker/domain/member/Member.java
> +        return this;
리뷰주신 의도를 잘못파악했던것 같습니다. 

처음 if문에서 null 체킹을 했을 때, 예외를 발생시키는 것을 의도하셨을까요??

2022-06-18 10:32 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/service/MemberService.java
> +    }
> save()를 사용하지 않고 처리할 수 있는 방법이 있을까요?

이 부분은 저도 JPA 처음 할 때 많이 실수했던 내용 중 하나에요.
결론부터 말하면 `없습니다.`

왜 인지 생각해보시면 좋을 것 같아요.
면접 질문으로도 잘 나오는 것 중 하나입니다. hint. entity life cycle

2022-06-18 10:40 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/domain/member/Member.java
>      }
`public isUpdateable()`의 존재로 전형적인 절차지향의 코딩이 되게 됩니다.
만약 사용자가 `isUpdateable()`을 호출하지 않고 `update()`를 쓰게 되면 어떻게 되나요?
처음과 같은 문제가 발생할 것입니다.

`묻지 말고 시켜라` 에 대해 공부해보시면 좋을 것 같습니다.

2022-06-18 10:41 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/domain/member/Member.java
> +        return this;
https://github.com/codesquad-members-2022/issue-tracker/pull/83#discussion_r900808750

outdate 된 관계로 위의 코멘트로 이어집니다.

2022-06-18 10:43 UTC, Hyune-c commented on BE/src/main/java/com/ron2ader/issuetracker/service/MemberService.java
> +    }
참고로 처음 작성한 로직이 이상한 것은 아닙니다.
로직적으로 구현할 수 있는 방법은 방법이 매우 많습니다.

하지만 클린 코딩의 관점에서 그중에서 더 보편적이고, 가독성 좋고, 간결한 방법을 찾는 과정이 필요합니다.

2022-06-18 11:57 UTC, Hyune-c approved these changes

2022-06-18 12:03 UTC, merged