[BE][team-36] sally 2번째 PR
codesquad-members-2022/issue-tracker pull request #95
Opened 2022-06-17 08:52 UTC by sally-ksh

왕민! 안녕하세요.
이번에도 크게 작업한 부분은 없습니다. ..🙂

서버 배포를 기본부터 한다는 생각으로 시작 했는데요.
처음 git 저장소랑 프로젝트 생성시 쉘 스크립트에서 여러부분에서 삽질하고 있습니다. (배포 베놈)
...좀 자신 없어지지만, 주말 동안 최대한 배포 자동화 등 시도해 보고자 하고 있습니다.

로그인 과정과 첨부 파일 과정에 질문이 있습니다.

#### 로그인

![image](https://user-images.githubusercontent.com/96989782/174261582-fc04e8b4-5e70-4c1d-bfd4-6e0282ad24fe.png)

- 위 로직으로 되지 않을까 정리 했는데요. 
  처음 접속하는 사용자가 로그인 요청할 때, 화면의 링크를 따라 FE에서 Authorization Server로 요청이 간다고 생각했습니다.
  근데 로그아웃  이후, OAuth 가입 사용자가 다시 로그인 버튼을 누를 때 처음과 다르게 가야 하는데,
  이 부분을 FE에서 확인하고 처리 하는 게 맞지 않을까 생각을 했는데요. 
  서버에서 처리 하는 방법도 들어서 .. 물어 봅니다.
  
#### 첨부파일

- FE 분들과 얘기 하다 보내 Git 글쓰기 등에 이미지를 올리면 url로 변경되는 데, 
  글쓰기 취소하고 이미지 저장하지 않아도, 시크릿 창 등에서 이미지가 그래도 유지 되는걸 이번에 알게 됐습니다.
  ... BE에서 어떻게 구현해야 하는지... 알려주시면 감사하겠습니다. 
  
  
  리뷰 감사합니다.
  좋은 주말 보내세요

2022-06-18 18:45 UTC, Min-92 requested changes
안녕하세요 샐리:)

질문 주신 부분은 아래에 답변 드립니다 :)
코멘트 드린부분도 확인해주세요.

현재 pr에 충돌이 발생한걸로 보이네요. 충돌 해결 한 후 리뷰 재요청 주시면 머지하도록 하겠습니다 :)
한주동안 고생 많으셨습니다.

--- 

- git 저장소 문제
git branch set upstream 으로 검색해보시죠 :)

- 로그인
어떤게 질문인지 잘 모르겠네요;;

- 첨부파일

글작성을 하지 않아도 첨부했던 이미지가 유지된다는 말씀이시죠?
```
이미지 저장 api를 추가.
-> fe에서 파일이 추가 될 떄마다 해당 api로 이미지 저장 요청. 
-> 서버에서는 이미지를 저장하고 url을 응답.

-> 글 작성시 이미지 url을 포함한 html tag 형식(or 마크다운 형식) content를 저장 요청
```
하면 해결이 가능하겠네요.

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/milestone/MilestoneApiController.java
> +	@GetMapping("/list")
rest api 설계의 경우 복수형 명사를 사용합니다.

GET /milestones
GET /milestones/id

[그런 rest api로 괜찮은가](https://www.youtube.com/watch?v=RP_f5dMoHFc&ab_channel=naverd2)

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/milestone/MilestoneRepository.java
> +	List<Milestone> findAllByProjectProjectId(Long projectId);
```suggestion
	List<Milestone> findAllByProjectId(Long projectId);
```

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/project/Project.java
> +	private Long projectId;
MilestoneId 코멘트와 동일합니다.

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/milestone/MilestoneService.java
> +	}
👍

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/milestone/MilestoneService.java
> +	}
```suggestion
	@Transactional
	public MilestoneResponse create(MilestoneRequest.Creation creationRequest, AuthUser authUser) {
		Project project = projectService.get(authUser.getProjectId());
		Milestone milestone = creationRequest.toMilestone(project);
		return MilestoneResponse.from(milestoneRepository.save(milestone));
	}
```

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/milestone/MilestoneService.java
> +			.collect(Collectors.toList());
💯

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/milestone/MilestoneService.java
> +			.collect(Collectors.toList());
좀 극단적이긴 하지만, 지역변수를 선언하지 않는다면?

```suggestion
	@Transactional(readOnly = true)
	public List<MilestoneResponse> readAll(AuthUser authUser) {
		return milestoneRepository.findAllByProjectProjectId(authUser.getProjectId())
			.stream()
			.map(Milestone::toDto)
			.collect(Collectors.toList());
		
```

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/milestone/dto/MilestoneRequest.java
> +	}
👍

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/milestone/dto/MilestoneResponse.java
> +@Builder
dto 클래스에 builder 패턴은 오버스펙으로 보입니다.
빌더패턴 사용 이유에 대해서 알아봅시다 :)

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/project/ProjectService.java
> +	}
MilestoneService.create 메소드에서 프로젝트가 없는경우가 고려 됐을까? 했는데 예외처리가 잘 되어있군요 💯

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/project/ProjectService.java
> +	}
예외의 경우 RuntimeException보다 명시적으로 예외상황에 알맞은 예외를 사용하는게 좋습니다.

2022-06-18 18:45 UTC, Min-92 commented on BE/src/main/java/com/sh/issuetracker/project/ProjectService.java
> +	}
찾는 아이템이 없는경우 null을 응답하거나, 예외를 발생 시키는 경우 메소드 이름으로 행동 표현이 가능합니다.


ex)
``` 
getOrNull
getOrThrow
```

명시적으로 동작을 표현해주면 사용하는 곳(MilestoneService.create 메소드)에서 동작을 쉽게 예측할 수 있습니다.

2022-06-18 18:45 UTC, Min-92 commented on BE/src/test/java/com/sh/issuetracker/milestone/MilestoneRepositoryTest.java
> +	@DisplayName("요청받은 마일스톤 데이터를 마일스톤 저장소에 저장됨을 확인한다.")
테스트 설명 or 테스트 명의 경우 ~는 ~를 ~한다 같은 형식으로 선언하기도 합니다.

https://hilucky.tistory.com/216

2022-06-18 18:45 UTC, Min-92 commented on BE/src/test/java/com/sh/issuetracker/milestone/MilestoneRepositoryTest.java
> +@DataJpaTest
DataJpaTest의 경우 Transactional어노테이션이 사용되고 있는데요.
해당 어노테이션이 없으면 어떤 일이 발생할까요?

2022-06-19 08:12 UTC, sally-ksh commented on BE/src/main/java/com/sh/issuetracker/milestone/Milestone.java
> +	}
dto 패키지를 별도로 두면서 접근제어자를 default 로도 안되어, 게터를 사용 안 해보고자 했는데,
리뷰어님 말씀 듣고 생각해 보니, 의존성 방향이 dto를 향하는게 좋진 않아 보입니다.
변경도 Dto에서 더 많을 것 같고, 수정하겠습니다.
리뷰 감사합니다~ 👍

2022-06-19 08:36 UTC, sally-ksh commented
작업이 늦어질 거 같아요 ㅎㅎ
완성 되는 대로 고쳐서 재요청 하겠습니다~

2022-06-19 14:00 UTC, sally-ksh commented on BE/src/main/java/com/sh/issuetracker/milestone/dto/MilestoneResponse.java
> +@Builder
``` java
@Builder(access = AccessLevel.PRIVATE)
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
@Getter
```

기존 코드에서는 @Data 로 setter 등이 쓰이는데,..
builder 패턴으로 과해 졌다는 생각이 들었습니다.

하지만, 정적 팩토리 메서드 내에서 
생성자 통해 생성시키기 보다 가독성이 좋다는 생각이 들었습니다.

그래서 수정을 해본 게,
응답 객체라서 final 선언이 가능하고, 불변객체로 되면서,
@Data를 제거하면서 수정해 봤습니다.
(Data 애노테이션도 자제해서 쓰는 게 좋을까 생각이 들었습니다.)
리뷰어님 의견에 맞춰 변경하면서,
엔티티 객체로부터 getter로 데이터를 전달 하다보니,
dto도 생성 등에 제한을 해주면 안정적이지 않을까 생각이 들었어요.

2022-06-19 14:03 UTC, sally-ksh commented on BE/src/test/java/com/sh/issuetracker/milestone/MilestoneRepositoryTest.java
> +@DataJpaTest
롤백이 안 되어 테스트로 넣은 데이터가 남게 됩니다.... ㅎㅎ

2022-06-19 14:05 UTC, Min-92 commented
코멘트 드린부분은 pr머지 후 다음에 수정하셔도 됩니다. 충돌해결되면 머지할게요

2022-06-19 14:27 UTC, sally-ksh commented on BE/src/main/java/com/sh/issuetracker/milestone/Milestone.java
> +@EqualsAndHashCode(of = "milestoneId")
toString은 제가 테스트로 돌아가도, 현재는 테스트 작성도 미숙하다 보니, 확인용으로 쓰는데, 지우겠습니다.
EqualsAndHashCode는 연관관계 맵핑관련하여 Issue 엔티티에서 쓰일 거라 작성했습니다.

2022-06-20 00:07 UTC, Min-92 commented
안녕하세요 샐리.
pr머지 위해서 충돌 해결 이후 커밋들은 취소 부탁드릴게요.

2022-06-20 02:18 UTC, Min-92 approved these changes

2022-06-20 02:18 UTC, merged